### ISSUE TITLE
Please add a new section describing the recommended process for upgrading the ADK.

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/commercialization-public#133]
ADK is referenced in several locations but I can't find any information regarding the upgrade of existing versions of the ADK, specifically when integrated into ConfigMgr and installed on a site server. The process is generally to uninstall the old version, reboot, install the new version then reboot again. Without the reboots, we've had issues with the ADK not working properly after installing the new version.  You can see a discussion thread here for the latest version https://twitter.com/ip1/status/1001263533022035968. 

Please add a new section describing the recommended process for upgrading the ADK.

https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install
https://docs.microsoft.com/en-us/windows/deployment/windows-adk-scenarios-for-it-pros
https://docs.microsoft.com/en-us/sccm/osd/plan-design/infrastructure-requirements-for-operating-system-deployment
https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/support-for-windows-10#windows-10-adk

**Comment by dawnwood** [comment]
Hi @AdamGrossTX  Thank you for taking the time to write feedback. I'm looking into this now.

**Comment by dawnwood** [comment]
Hi again, I want to let you know that I've opened a tracking bug so that we can triage and assign the writing to someone on the writing team. I'm closing this issue because we're tracking this internally now. Thanks again for taking the time to provide feedback.
Best,
Dawn
