### ISSUE TITLE
Can not build image successfully

### ISSUE THREAD

**Issue by MichaelXlj** [MicrosoftDocs/commercialization-public#151]
I tried to build a image for Raspberry Pi via following the document.
But when i execute command "buildimage ProductA test", i get the error as following:

Creating ProductA test Image, see C:\iot-adk-addonkit\Build\arm\ProductA_test.log for progress
ThreadId26020 ERROR: Imaging!ValidateInput: Failed to load Feature Manifest XML file C:\iot-adk-addonkit\Build\arm\MergedFMs\RPi2FM.xml:FeatureAPI!ValidateAndLoad: FeatureManifest file was not found: C:\iot-adk-addonkit\Build\arm\MergedFMs\RPi2FM.xml
ThreadId26020 ERROR:    FeatureAPI!ValidateAndLoad: FeatureManifest file was not found: C:\iot-adk-addonkit\Build\arm\MergedFMs\RPi2FM.xml
Error : Build failed. See Log for details

IoTCoreShellv5.1 arm 10.0.0.0

I checked the detail information from the log file.

{6/8/2018 2:33:15 PM}  Imaging: Reading the OEM Input XML file...
{6/8/2018 2:33:15 PM}  FeatureAPI: Successfully validated the OEM Input XML: C:\iot-adk-addonkit\Source-arm\Products\ProductA\testOEMInput.xml
{6/8/2018 2:33:15 PM}  Imaging: Reading the FM XML file 'C:\iot-adk-addonkit\Build\arm\MergedFMs\RPi2FM.xml'...
{6/8/2018 2:33:15 PM} Error: Imaging!ValidateInput: Failed to load Feature Manifest XML file C:\iot-adk-addonkit\Build\arm\MergedFMs\RPi2FM.xml:FeatureAPI!ValidateAndLoad: FeatureManifest file was not found: C:\iot-adk-addonkit\Build\arm\MergedFMs\RPi2FM.xml
{6/8/2018 2:33:15 PM} Error: 	FeatureAPI!ValidateAndLoad: FeatureManifest file was not found: C:\iot-adk-addonkit\Build\arm\MergedFMs\RPi2FM.xml
{6/8/2018 2:33:15 PM}  Imaging: See Flash.cbs.log for details.
{6/8/2018 2:33:15 PM}  Imaging: Performance Results:
{6/8/2018 2:33:15 PM}  	Total Run Time:	00:00:00.1580018
{6/8/2018 2:33:15 PM}  	Storage Stack Time:	00:00:00.0000002
{6/8/2018 2:33:15 PM}  	Total run time:	158.0018ms
{6/8/2018 2:33:15 PM}  	Total staging time:	0ms
{6/8/2018 2:33:15 PM}  	Total commit time:	0ms
{6/8/2018 2:33:15 PM}  	CompDB Total Time (ms):	0ms
{6/8/2018 2:33:15 PM}  	Image format:	FFU
{6/8/2018 2:33:15 PM}  	Stage file time:	0
{6/8/2018 2:33:15 PM}  	UpdateOS time:	0

I think there are some files missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f7b1fcf-a299-2f26-e2bb-9acc4f7fa6b4
* Version Independent ID: b0a6652d-54eb-7416-059d-a1c86fda93ac
* Content: [Lab 1a: Create a basic image](https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/create-a-basic-image)
* Content Source: [manufacture/iot/create-a-basic-image.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/iot/create-a-basic-image.md)
* Product: **windows-hardware**
* GitHub Login: @kpacquer
* Microsoft Alias: **themar**

**Comment by MichaelXlj** [comment]
I copied the RPi2FM.xml file from '\IoT-ADK-AddonKit\Source-arm\BSP\Rpi2\Packages' folder to  '\IoT-ADK-AddonKit\Build\arm\MergedFMs'. It can resolve the issue. I think the document need to be update for this issue.

**Comment by MichaelXlj** [comment]
It seems that in the bsp zip file, the *.wm.xml files missed.

**Comment by parameshbabu** [comment]
Yes. you can use the latest zip file or use convertpkg.cmd before running build.cmd file.
