### ISSUE TITLE
Errors in Reinstall Inbox Apps script

### ISSUE THREAD

**Issue by immortalking** [MicrosoftDocs/commercialization-public#161]
/package: should be /PackagePath:
/license should be /LicensePath:
/Dependencypackage: should be /DependencyPackagePath:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27ce5a02-7fa2-6a17-2588-6d591d9533d6
* Version Independent ID: 25c58b78-2436-3ef9-3b5c-8c9a8b038a52
* Content: [Sample scripts](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-deployment-sample-scripts-sxs#span-idreinstallwindowsinboxappsspanreinstall-windows-inbox-apps)
* Content Source: [manufacture/desktop/windows-deployment-sample-scripts-sxs.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/windows-deployment-sample-scripts-sxs.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
I corrected the errors in the script and merged it to master.
