### ISSUE TITLE
SignTool Error: No certificates were found that met all the given criteria.

### ISSUE THREAD

**Issue by MichaelXlj** [MicrosoftDocs/commercialization-public#163]
When i followed this guide to build retail image, i encountered this error:
```
ThreadId28472 ERROR: (0,0):
ERROR: 0x80131500
ERROR: PkgGen
ERROR: EXCEPTION: ExecuteCommands::Run:cmd.exe /c sign.cmd  "C:\Work\iot-adk-addonkit\Build\arm\Temp\24e32lku.4pg\update.cat" failed.
SignTool Error: No certificates were found that met all the given criteria.

Err: 1
ERROR: STACKTRACE:   at Microsoft.Composition.ToolBox.ExecuteCommands.Run(String toolPath, String args, Boolean loadUserProfile, UInt32 retryCount, Logger logger)
ERROR:   at Microsoft.Composition.ToolBox.Security.SecurityToolBox.SignFile(String filePath, Boolean testOnly, SigningHashAlgorithm algo)
ERROR:   at Microsoft.Composition.Packaging.PkgManifest.GenerateAndSignCatalog(Boolean signCatalog)
ERROR:   at Microsoft.Composition.Packaging.PkgManifest.SerializeMum(String outputFolder)
ERROR:   at Microsoft.Composition.Packaging.PkgManifest.SaveManifest(String outputFolder)
ERROR:   at Microsoft.Composition.Packaging.CbsPackage.SavePackage(String outputFolder, Boolean compressManifests)
ERROR:   at Microsoft.Composition.Packaging.CbsPackage.SavePackage(String outputFolder)

(PkgToolBox) : error : ExecuteCommands::Run:cmd.exe /c sign.cmd  "C:\Work\iot-adk-addonkit\Build\arm\Temp\24e32lku.4pg\update.cat" failed.
SignTool Error: No certificates were found that met all the given criteria.

Err: 1
Error : Failed to create package. See C:\Work\iot-adk-addonkit\Build\arm\pkgs\logs\Appx.DigitalSign.wm.log
```

I checked this log file, got this infomation:

```
ThreadId28472 INFO Running cmd.exe /c sign.cmd  "C:\Work\iot-adk-addonkit\Build\arm\Temp\24e32lku.4pg\update.cat"
ThreadId28472 INFO signtool.exe sign /v /s my /i "Issuer" /n "Subject" /ac "CrossCertRoot" /fd SHA256  /t http://timestamp.verisign.com/scripts/timestamp.dll   "C:\Work\iot-adk-addonkit\Build\arm\Temp\24e32lku.4pg\update.cat"
signtool.exe : fatal error : Signing failed with 1 on "C:\Work\iot-adk-addonkit\Build\arm\Temp\24e32lku.4pg\update.cat"
Sign.Cmd RC=1
```

It seems that the timestamp service is disable.
If i comment the _SIGNTOOL_OEM_SIGN_  in setsignature.cmd, it works, command _buildpkg all_ will be executed successfully.How to fix this issue? Any suggestion will be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7859472-d6d6-186e-09d4-14fddb3b8dba
* Version Independent ID: 9824242c-14be-497f-a92b-2a4e506ec7d0
* Content: [Lab 1f: Build a retail image](https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/build-retail-image)
* Content Source: [manufacture/iot/build-retail-image.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/iot/build-retail-image.md)
* Product: **windows-hardware**
* GitHub Login: @kpacquer
* Microsoft Alias: **themar**

**Comment by parameshbabu** [comment]
SignTool Error: No certificates were found that met all the given criteria - This error signifies that the certificate is not installed on the machine and is not able to pick that up. You can solve this by re-running the InstallOemCerts.cmd (after installing the latest 1803 ADK).
