### ISSUE TITLE
Battery Indicators are different at different UIs.

### ISSUE THREAD

**Issue by wayyt** [MicrosoftDocs/commercialization-public#164]
This article mentions “Windows provides indication of power source and battery status in the operating system. This is presented to the user in several places, including the battery tray icon on the desktop, on the Start menu, and directly on the Lock screen.”

But I found Battery Indicators are different at different UIs in Windows 10 RS3 and RS4. Looks there is a bug in Windows 10.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc7852e-fb00-457a-9f91-7ef4a8a706b0
* Version Independent ID: ca254542-4b31-b869-eff8-349623f03178
* Content: [Battery and power subsystem hardware design](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/battery-and-power-subsystem-hardware-design)
* Content Source: [design/device-experiences/battery-and-power-subsystem-hardware-design.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/design/device-experiences/battery-and-power-subsystem-hardware-design.md)
* Product: **windows-hardware**
* GitHub Login: @Joshua Baxter
* Microsoft Alias: **dongill**

**Comment by dawnwood** [comment]
Hi @wayyt thank you for your feedback. Can you tell me a bit more about what is happening on Windows 10? For example, how did you find the discrepancy between Windows 10 RS3 and RS4? What were the circumstances?

**Comment by dawnwood** [comment]
Hi @wayyt Due to the length of time it's been since you opened this issue, I assume that your problem is resolved. 
Please reopen if you are still experiencing issues.
