### ISSUE TITLE
If RegisteredOwner is blank?

### ISSUE THREAD

**Issue by steve6375** [MicrosoftDocs/commercialization-public#166]
If RegisteredOwner is blank in the XML file, then the random computername seems to comprise of the first seven letters of the user name (not sure which exact field in XML file is used) plus a hyphen plus seven random characters.
How RegisteredOwner and RegisteredOrganization is used **exactly** in the random computername generation is not specified?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbfbb7a5-4f30-6ce8-6297-f4d464d84d38
* Version Independent ID: d29b3d67-c73e-bece-5cad-df84da05eb81
* Content: [ComputerName](https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-shell-setup-computername)
* Content Source: [customize/desktop/unattend/microsoft-windows-shell-setup-computername.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/customize/desktop/unattend/microsoft-windows-shell-setup-computername.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by steve6375** [comment]
From my experiments, when ComputerName=* the final computername is made from up to the first 7 characters of FullName followed by Organization, e.g.
ComputerName=*
FullName=UF552
Organization=E2B
Result >>> Computer name is set to UF552E2-N42R1CJ
The documentation seems totally wrong, at least for Win 10 1709  Build 16299!

**Comment by steve6375** [comment]
Is ComputerName="" valid and is it same as a blank entry?
I am unsure when or where using double quotes for a value is valid in XML files...

**Comment by steve6375** [comment]
It's not 'fullname and/or organization'.
It should say up to the first 7 characters of fullname followed by the first characters of organisation to make a total of 7 characters, which is then followed by a hyphen and 7 random characters to make a 15 character computername.

**Comment by kpacquer** [comment]
"" is a blank entry.
Updated again, thanks for the feedback!

**Comment by steve6375** [comment]
Try
Fullname=WA
Organization=S
ComputerName=*

**Comment by VictorKleist** [comment]
If I set ComputerName=*  it will give me a randon number? i'm trying to set the serialnumber instead of a randon one

**Comment by steve6375** [comment]
Well just set the ComputerName to whatever string you want. There is no provision to automatically set the serial number. Where does the Serial Number comes from? Where is it stored? How can it be retrieved? Different Serial numbers are stored in different locations on different computers by different manufacturers, There is no standard way to retrieve the 'Serial Number'.
