### ISSUE TITLE
Unable to download pre-generated report listed in this page.

### ISSUE THREAD

**Issue by pali23** [MicrosoftDocs/commercialization-public#167]
"Download the pre-generated sleepstudy-report_2.html report here."

I'm unable to download the file listed here:

URL : http://download.microsoft.com/download/3/2/E/32E8B553-47F6-4E2A-9109-C6D678FE0EE8/sleepstudy-report_2.mdl

Getting following error:
This site can’t be reached
The webpage at http://download.microsoft.com/download/3/2/E/32E8B553-47F6-4E2A-9109-C6D678FE0EE8/sleepstudy-report_2.mdl might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

Please check.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13170343-90da-adaf-31ca-8f727cd4ea33
* Version Independent ID: 262a3f01-888f-7dee-99aa-b7f513278683
* Content: [Exercise 2 - Identify Problems with Missing Drivers](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/debugging-problems-with-standby-exercise-2#feedback)
* Content Source: [test/wpt/debugging-problems-with-standby-exercise-2.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/test/wpt/debugging-problems-with-standby-exercise-2.md)
* Product: **windows-hardware**
* GitHub Login: @Joshua Baxter
* Microsoft Alias: **eliotgra**

**Comment by aahill** [comment]
Hi @pali23, thanks for letting us know about this. It looks like the url may have been malformed. Replacing .mdl with .html gives me a valid URL
 http://download.microsoft.com/download/3/2/E/32E8B553-47F6-4E2A-9109-C6D678FE0EE8/sleepstudy-report_2.html

Is this the file you're looking for? If so, I'll add it to the documentation. Thanks!

**Comment by pali23** [comment]
Thanks, this is the file I'm looking for.
Please update same in webpage.

Regards,
Abhishek

**Comment by aahill** [comment]
Great, happy to help!
