### ISSUE TITLE
The docs should update for 1803!

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/commercialization-public#168]
For example:
1. Review the package definition file: Provisioning.Auto.wm.xml: C:\IoT-ADK-AddonKit\Common\Packages\Provisioning.Auto\Provisioning.Auto.wm.xml.
There is no "Provisioning.Auto" within the "Packages" folder, but there is one in the "ProdPackages" folder.
2. The content of the "Provisioning.Auto.wm.xml" is not same as the website lists.
3. There is no feature ID: OEM_ProvAuto, but there is a feature ID: ProvAuto within the file.
etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee5787f1-274d-4529-8b1d-f1f00e636861
* Version Independent ID: ef4beb8d-f439-82ff-b8ea-dcc83659ca6b
* Content: [Lab 1d: Add networking and other provisioning package settings to an image](https://docs.microsoft.com/EN-US/windows-hardware/manufacture/iot/add-a-provisioning-package-to-an-image)
* Content Source: [manufacture/iot/add-a-provisioning-package-to-an-image.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/iot/add-a-provisioning-package-to-an-image.md)
* Product: **windows-hardware**
* GitHub Login: @kpacquer
* Microsoft Alias: **themar**

**Comment by parameshbabu** [comment]
Docs updated.

**Comment by parameshbabu** [comment]
Pull Request 9539: iot core guide revision - fixing errors and updating to latest status of the tools
