### ISSUE TITLE
File/Folder based exceptions are listed in UWF_Overlay provider

### ISSUE THREAD

**Issue by kszydlo** [MicrosoftDocs/commercialization-public#170]
Hi, 
I've been working on a TC image for my org. I'm concerned about our write-filter overlay consumption. I used the above providers to find the files hitting the overlay. What's concerning about it is that things I've defined filter exceptions for are still showing up in my write-filter overlay.

Here's info on the system(s) I've checked.
#Hardware Info 
HP MT-21 Mobile Thin Client
x64 processor
8gb RAM
120gb m.2 drive

#OS Version
Windows 10 Enterprise 2016 LTSB (Build 10.0.14393)

#UWF Config
uwfmgr volume protect C:

uwfmgr file add-exclusion C:\ProgramData\Sophos
uwfmgr file add-exclusion "C:\Program Files (x86)\Sophos"
uwfmgr file add-exclusion C:\Windows\CCM\UserAffinityStore.sdf
uwfmgr file add-exclusion C:\Windows\CCM\InventoryStore.sdf
uwfmgr file add-exclusion C:\Windows\CCM\CCMStore.sdf
uwfmgr file add-exclusion C:\Windows\CCM\StateMessageStore.sdf
uwfmgr file add-exclusion C:\Windows\CCM\CertEnrollmentStore.sdf

#UWF-OverlaySize
uwfmgr overlay set-size 2048
uwfmgr overlay set-warningthreshold 1024
uwfmgr overlay set-criticalthreshold 1536 

#UWF Enablement
uwfmgr.exe filter enable

#Scripting to determine contents of write-filter overlay
#Derived from technet https://docs.microsoft.com/en-us/windows-hardware/customize/enterprise/uwf-wmi-provider-reference
function Get-OverlayNamespace { Get-WmiObject -Namespace root\standardcimv2\embedded -Class UWF_Overlay }
function Get-OverlayContents { (Get-OverlayNamespace).GetOverlayFiles((Get-Volume C).uniqueID) }
function Show-OverlayFiles {
    Write-Host "Caching the overlay is time intensive. This can take several minutes to complete." -ForegroundColor Yellow
   (Get-OverlayContents).overlayfiles | Select-Object @{l='Size in KB';e={($_.filesize / 1kb)}},Filename &gt;&gt; $FILENAME.txt 
}
   

#Exerts from Show-OverlayFiles that are concerning
136k	\Windows\CCM\CcmStore.sdf::$DATA
8k	\Windows\CCM\StateMessageStore.log::$DATA
13676k  \Windows\CCM\InventoryStore.sdf::$DATA
56k	\Windows\CCM\UserAffinityStore.sdf::$DATA
20k	\ProgramData\Sophos\Remote Management System\3\Agent\AdapterStorage\SAV\SAVAdapterConfig::$DATA
12k	\ProgramData\Sophos\Remote Management System\3\Agent\Logs\Agent-20180612-162436.log::$DATA
12k	\ProgramData\Sophos\Remote Management System\3\Agent\Logs\Agent-20180613-160349.log::$DATA
12k	\ProgramData\Sophos\Remote Management System\3\Router\Logs\Router-20180612-162436.log::$DATA
5100k	\ProgramData\Sophos\Sophos Anti-Virus\Cache\b8ee0e5ffcc04d13b4c870dee8def89d.cache::$DATA
44k	\ProgramData\Sophos\Sophos Anti-Virus\Config\machine.xml::$DATA
8k	\ProgramData\Sophos\Sophos Anti-Virus\logs\SAV-Trace.txt::$DATA
572k	\Program Files (x86)\Sophos\Sophos Anti-Virus\appc01.vdb::$DATA
32k	\Program Files (x86)\Sophos\Sophos Anti-Virus\cidsync.upd::$DATA
16k	\Program Files (x86)\Sophos\Sophos Anti-Virus\cln01.vdb::$DATA
24k	\Program Files (x86)\Sophos\Sophos Anti-Virus\savsync.upd::$DATA
16k	\Program Files (x86)\Sophos\Sophos Anti-Virus\sus01.vdb::$DATA
384k	\Program Files (x86)\Sophos\Sophos Anti-Virus\vdl01.vdb::$DATA
20k	\Program Files (x86)\Sophos\Sophos Anti-Virus\vdl.dat::$DATA
324k	\Program Files (x86)\Sophos\Sophos Anti-Virus\vdl02.vdb::$DATA
268k	\Program Files (x86)\Sophos\Sophos Anti-Virus\vdl03.vdb::$DATA
240k	\Program Files (x86)\Sophos\Sophos Anti-Virus\vdl04.vdb::$DATA
    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bd391d7-be32-580d-4900-014f3d4e3720
* Version Independent ID: b2f1967c-b2b8-7ad5-4a3e-3fd28e5c0c0b
* Content: [Unified Write Filter WMI provider reference](https://docs.microsoft.com/en-us/windows-hardware/customize/enterprise/uwf-wmi-provider-reference)
* Content Source: [customize/enterprise/uwf-wmi-provider-reference.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/customize/enterprise/uwf-wmi-provider-reference.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by kpacquer** [comment]
I'm sorry you're having issues with your write-filter overlay, but I can't troubleshoot it for you. The best way to get help would be to contact Microsoft Support (https://support.microsoft.com/en-us/contactus/), or you can post in the Forum (https://social.technet.microsoft.com/Forums/windows/en-US/home?forum=win10itprogeneral).
