### ISSUE TITLE
How to detect whether system will start "BitLocker automatic device encryption"?

### ISSUE THREAD

**Issue by PTP4FJ** [MicrosoftDocs/commercialization-public#175]
Any correlation to the "DG and CG HW readiness tool" results? 
(https://www.microsoft.com/en-us/download/details.aspx?id=53337)
What we have to check for?
Would really like to have a script ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51422c26-8933-adfb-6865-d4b8e6f39a97
* Version Independent ID: 3aae9a69-4faa-c3b9-ea12-e4968106d115
* Content: [BitLocker drive encryption in Windows 10 for OEMs](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-bitlocker)
* Content Source: [design/device-experiences/OEM-bitlocker.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/design/device-experiences/OEM-bitlocker.md)
* GitHub Login: @DawnWood

**Comment by Justinha** [comment]
@PTP4FJ You can use Start > msinfo. At the bottom of the results there is an entry for Device Encryption Support with status.

**Comment by PTP4FJ** [comment]
![bitlocker](https://user-images.githubusercontent.com/40469322/41783280-022f5920-762c-11e8-9d8a-6d7f836f7ddd.jpg)
After OOBE from preinstalled Win10 RS3 with “local account”:
  Bitlocker Version:          2.0
  Conversion Status:        Used space only encrypted
  Percentage Encrypted:  100%
  Protection Status:          Off
  Key Protection:               None
