### ISSUE TITLE
Good page

### ISSUE THREAD

**Issue by legspeed** [MicrosoftDocs/commercialization-public#180]
This is a good page with a clear explanation of pen states.  It helped me understand how to configure my Surface pen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0163edd-7887-481e-68ff-177120471181
* Version Independent ID: 73c72e15-6ee6-9672-7461-80825e457640
* Content: [Windows Pen States](https://docs.microsoft.com/en-us/windows-hardware/design/component-guidelines/windows-pen-states)
* Content Source: [design/component-guidelines/windows-pen-states.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/design/component-guidelines/windows-pen-states.md)
* Product: **windows-hardware**
* GitHub Login: @Joshua Baxter
* Microsoft Alias: **dongill**

**Comment by themar-msft** [comment]
Thanks for the feedback!
