### ISSUE TITLE
App-V is missing

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/commercialization-public#181]
Looks like someone forgot to include App-V in the 1803 ADK.  It's missing from the selectable options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5da42cd-bec2-defe-587f-5696d382db49
* Version Independent ID: dd337af7-d30a-d357-1e97-45ecd778e139
* Content: [What's new in the Windows ADK and ADK tools](https://docs.microsoft.com/en-us/windows-hardware/get-started/what-s-new-in-kits-and-tools)
* Content Source: [get-started/what-s-new-in-kits-and-tools.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/get-started/what-s-new-in-kits-and-tools.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by themar-msft** [comment]
When running the installer for 1803 from this page, the app v sequencer option is one of the selectable choices:

![image](https://user-images.githubusercontent.com/33436507/41864268-3133123c-785e-11e8-8bb7-ef221d9b6b31.png)

**Comment by jordanmills** [comment]
Really?  Just "no" and close the report?

![image](https://user-images.githubusercontent.com/6401772/41875673-4cf50aec-7891-11e8-9c64-53834bb94db5.png)
