### ISSUE TITLE
Kernel-Mode Drive Framework link leading to a 404 page

### ISSUE THREAD

**Issue by Yegmorcar** [MicrosoftDocs/commercialization-public#182]
The link that says: Kernel-Mode Driver Framework (URL: http://go.microsoft.com/fwlink/?LinkId=143072) does not function. It leads to a "We are sorry, the page you requested cannot be found." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f34544b-0b7b-3b6e-1334-a413246d1b47
* Version Independent ID: 3ca9ad79-41f5-7503-4e13-9ec53c2760d9
* Content: [Microsoft-Windows-WDF-Kernel Library](https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-wdf-kernel-library)
* Content Source: [customize/desktop/unattend/microsoft-windows-wdf-kernel-library.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/customize/desktop/unattend/microsoft-windows-wdf-kernel-library.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by aahill** [comment]
Looks like the fwlink is going to: https://www.microsoft.com/whdc/driver/wdf/KMDF.mspx
