### ISSUE TITLE
"CurrentSesson" is error

### ISSUE THREAD

**Issue by Yangxing1995** [MicrosoftDocs/commercialization-public#183]
class UWF_Servicing {
    [key, read] boolean CurrentSesson;
    [read] boolean ServicingEnabled;

    UInt32 Enable();
    UInt32 Disable();
    UInt32 UpdateWindows(
        [out] UInt32 UpdateStatus
    );
};

"CurrentSesson" is error, it is "CurrentSession".

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: de804aeb-33a9-603a-09fe-ee460fee0889
* Version Independent ID: 3655d52c-08a1-42a1-42b8-ddf2eae3d02f
* Content: [UWF\_Servicing](https://docs.microsoft.com/zh-cn/windows-hardware/customize/enterprise/uwf-servicing)
* Content Source: [customize/enterprise/uwf-servicing.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/customize/enterprise/uwf-servicing.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by kpacquer** [comment]
You're right, thanks for letting us know! Fixing the example.
