### ISSUE TITLE
Where is the table for settings which can be used to set the standby budget?

### ISSUE THREAD

**Issue by guliteb** [MicrosoftDocs/commercialization-public#184]
In &lt;Standby budget setting&gt; section, it mentioned 'The following table lists the settings you can use to set the standby budget, which is the amount of battery the user is allowed to drain during standby'.

But I cannot find the table. Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193642df-5de4-8f05-d5bc-9ed0d9e156e8
* Version Independent ID: 568e289d-3c11-5069-6052-1f4d298302cb
* Content: [Adaptive Hibernate](https://docs.microsoft.com/en-us/windows-hardware/customize/power-settings/adaptive-hibernate#standby-budget-setting)
* Content Source: [customize/power-settings/adaptive-hibernate.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/customize/power-settings/adaptive-hibernate.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by themar-msft** [comment]
Thanks for letting us know. It looks like the text is referencing the table above (StandbyBudgetPercent). I'll fix the topic.
