### ISSUE TITLE
How to Block keys for particular user account

### ISSUE THREAD

**Issue by Kanimozhi12** [MicrosoftDocs/commercialization-public#187]
Blocking keys using powershell script is working fine. but it affects the whole system (computer) . how can we apply this to particular user account alone?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3a9d83b-df25-06e2-6cc1-aa5cacced539
* Version Independent ID: 7626cc7d-14f2-cf57-18ae-4660fdb7f9f2
* Content: [Add blocked key combinations](https://docs.microsoft.com/en-us/windows-hardware/customize/enterprise/keyboardfilter-add-blocked-key-combinations)
* Content Source: [customize/enterprise/keyboardfilter-add-blocked-key-combinations.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/customize/enterprise/keyboardfilter-add-blocked-key-combinations.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by themar-msft** [comment]
Hi @Kanimozhi12 - See [Modify global settings](https://docs.microsoft.com/en-us/windows-hardware/customize/enterprise/modify-global-settings), which covers how to disable the Keyboard filter for administrators. Other than that, I don't believe that you can configure the keyboard filter for specific users.
