### ISSUE TITLE
Script BIOS or UEFI mode detection

### ISSUE THREAD

**Issue by lukebakare** [MicrosoftDocs/commercialization-public#190]
Just have a question about the comment: "Note that between delims= and " %%A is a tab, followed by a space."

Why is this the case and what does this functionally do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2094d9b5-5e48-dc3f-5c16-e0c95ced059d
* Version Independent ID: 27838fd7-6b5c-2a68-d139-0b49f356842f
* Content: [Boot to UEFI Mode or Legacy BIOS mode](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/boot-to-uefi-mode-or-legacy-bios-mode)
* Content Source: [manufacture/desktop/boot-to-uefi-mode-or-legacy-bios-mode.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/boot-to-uefi-mode-or-legacy-bios-mode.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
Hi Luke,

We put that note there because if you copy and paste the script, it will paste is as a series of spaces, but you need to have a tab and a space for the script to work.
