### ISSUE TITLE
Missing diagram

### ISSUE THREAD

**Issue by eliyasy** [MicrosoftDocs/commercialization-public#191]
&gt;&gt;&gt;The process for preparing the hardware for low-power during standby can be visualized as an upside-down pyramid as shown in the following diagram.

Where is the diagram? There are couple of places in the Modern standby section, there is a reference to non-existent diagrams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 062d5ba4-424f-6d51-591c-ad3055c62cbd
* Version Independent ID: 2b424a83-242a-4bbb-5a8a-5c28dcaeefd4
* Content: [Prepare hardware for modern standby](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/prepare-hardware-for-modern-standby)
* Content Source: [design/device-experiences/prepare-hardware-for-modern-standby.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/design/device-experiences/prepare-hardware-for-modern-standby.md)
* Product: **windows-hardware**
* GitHub Login: @Joshua Baxter
* Microsoft Alias: **dongill**

**Comment by themar-msft** [comment]
@eliyasy - Thanks for letting us know. I've updated the topic to include the diagram. The update should be published later today. In the meantime, here is the diagram:

![image](https://user-images.githubusercontent.com/33436507/41991050-0f498f7e-79f9-11e8-8829-9a4bc36634aa.png)
