### ISSUE TITLE
Diagram referenced in this page is missing

### ISSUE THREAD

**Issue by eliyasy** [MicrosoftDocs/commercialization-public#192]
Diagram referenced in this page is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc7852e-fb00-457a-9f91-7ef4a8a706b0
* Version Independent ID: ca254542-4b31-b869-eff8-349623f03178
* Content: [Battery and power subsystem hardware design](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/battery-and-power-subsystem-hardware-design)
* Content Source: [design/device-experiences/battery-and-power-subsystem-hardware-design.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/design/device-experiences/battery-and-power-subsystem-hardware-design.md)
* Product: **windows-hardware**
* GitHub Login: @Joshua Baxter
* Microsoft Alias: **dongill**

**Comment by themar-msft** [comment]
Hello @eliyasy - I've added the missing diagrams back. In the meantime, here they are:


-     Diagram 1:

     ![image](https://user-images.githubusercontent.com/33436507/41996412-ab485c4c-7a09-11e8-9e33-b33b4b32e3c1.png)



-     Diagram 2:

     ![image](https://user-images.githubusercontent.com/33436507/41996423-b3d0b6ca-7a09-11e8-99ab-ff65f6ecaf16.png)
