### ISSUE TITLE
Error: No package definition files found.

### ISSUE THREAD

**Issue by 549082452** [MicrosoftDocs/commercialization-public#196]
IOTADK_ROOT : E:\gitcode\iot-adk-addonkit
ADK_VERSION : 17134
WDK_VERSION : 17134
COREKIT_VER : 17134.1
OEM_NAME    : Contoso

Set Environment for Architecture
Choose 1 for ARM, 2 for x86 and 3 for x64 : 1

Configuring for arm architecture
KitsRoot       : [C:\Program Files (x86)\Windows Kits\10\]
WDKContentRoot : []
Retail Signing disabled
BSP_ARCH    : arm
BSP_VERSION : 10.0.0.0
BSPPKG_DIR  : E:\gitcode\iot-adk-addonkit\Build\arm\pkgs
MSPKG_DIR   : C:\Program Files (x86)\Windows Kits\10\MSPackages\Retail\arm\fre

IoTCoreShellv5.1 arm 10.0.0.0
.....
.....
E:\rpibsp&gt;build.cmd
signing E:\rpibsp\bcm2836pwm.sys
signing E:\rpibsp\bcm2836sdhc.sys
signing E:\rpibsp\bcmauxspi.sys
signing E:\rpibsp\bcmgpio.sys
signing E:\rpibsp\bcmi2c.sys
signing E:\rpibsp\bcmspi.sys
signing E:\rpibsp\pi_miniuart.sys
signing E:\rpibsp\rpiq.sys
signing E:\rpibsp\rpisdhc.sys
signing E:\rpibsp\rpiwav.sys
signing E:\rpibsp\SerPL011.sys
signing E:\rpibsp\vchiq.sys
signing E:\rpibsp\vchiq_arm_kern.dll
signing E:\rpibsp\vcos_win32_kern.dll
Building packages in E:\rpibsp\
Error: No package definition files found.
I don't know what's wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f7b1fcf-a299-2f26-e2bb-9acc4f7fa6b4
* Version Independent ID: b0a6652d-54eb-7416-059d-a1c86fda93ac
* Content: [Lab 1a: Create a basic image](https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/create-a-basic-image#feedback)
* Content Source: [manufacture/iot/create-a-basic-image.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/iot/create-a-basic-image.md)
* Product: **windows-hardware**
* GitHub Login: @kpacquer
* Microsoft Alias: **themar**

**Comment by parameshbabu** [comment]
RPi bsp link updated to https://github.com/ms-iot/iot-adk-addonkit/releases/download/v4.4/rpibsp-wm.zip

**Comment by parameshbabu** [comment]
Fixed with Pull Request 9539: iot core guide revision - fixing errors and updating to latest status of the tools
