### ISSUE TITLE
direct link for xperf

### ISSUE THREAD

**Issue by mailinglists35** [MicrosoftDocs/commercialization-public#198]
please give us direct link for installing just xperf
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78a7ade4-09ab-e0b2-4ace-a14b2d9c9bce
* Version Independent ID: 34de1342-2814-e81f-0f72-25395d07d6a6
* Content: [Download and install the Windows ADK](https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install)
* Content Source: [get-started/adk-install.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/get-started/adk-install.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by dawnwood** [comment]
Hi @mailinglists35 This sounds like feedback for a tool in the adk. Your feedback is better submitted in the Feedback Hub, that you can find by typing "Feedback Hub" in the Start menu.
Best,
Dawn

**Comment by mailinglists35** [comment]
offtopic, I wish now that Microsoft owns github to trow away the feedback hub and move all it's contents over here. I don't have enough time and patience to list all annoyances of FH
