### ISSUE TITLE
Settings for HKLM\SYSTEM\CurrentControlSet\Control\DmaSecurity\AllowedBuses

### ISSUE THREAD

**Issue by PTP4FJ** [MicrosoftDocs/commercialization-public#200]
When we add some entries to AllowedBuses key the "Device Encryption Support" in MSINFO32 meets prerequisites.
How should these be handled by the OEM for “classical desktops” where typical PCIE slots are present (we offer a lock in the higher end models)?
Is there a way to overcome the registry settings with additional HSTI?
(HSTI verification via DG/CG tool is OK!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51422c26-8933-adfb-6865-d4b8e6f39a97
* Version Independent ID: 3aae9a69-4faa-c3b9-ea12-e4968106d115
* Content: [BitLocker drive encryption in Windows 10 for OEMs](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-bitlocker#feedback)
* Content Source: [design/device-experiences/OEM-bitlocker.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/design/device-experiences/OEM-bitlocker.md)
* GitHub Login: @DawnWood

**Comment by dawnwood** [comment]
Hi @PTP4FJ My apologies for the delay in responding. Do you still have this question?

**Comment by dawnwood** [comment]
Hi @PTP4FJ Due to the length of time it's been since you opened this issue, I assume that your problem is resolved. 
Please reopen if you are still experiencing issues.
