### ISSUE TITLE
oobe

### ISSUE THREAD

**Issue by letme0ut** [MicrosoftDocs/commercialization-public#214]
MW v10.0.17134.1  why not hiding _?
&lt;?xml version="1.0" encoding="UTF-8"?&gt;

-&lt;unattend xmlns="urn:schemas-microsoft-com:unattend"&gt;

-&lt;settings pass="specialize"&gt;

-&lt;component language="neutral" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" versionScope="nonSxS" publicKeyToken="31bf3856ad364e35" processorArchitecture="wow64" name="Microsoft-Windows-Shell-Setup"&gt;

&lt;CopyProfile&gt;true&lt;/CopyProfile&gt;

&lt;/component&gt;

&lt;/settings&gt;

-&lt;settings pass="oobeSystem"&gt;

-&lt;component language="neutral" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" versionScope="nonSxS" publicKeyToken="31bf3856ad364e35" processorArchitecture="wow64" name="Microsoft-Windows-Shell-Setup"&gt;

-&lt;OOBE&gt;

&lt;HideEULAPage&gt;true&lt;/HideEULAPage&gt;

&lt;HideLocalAccountScreen&gt;true&lt;/HideLocalAccountScreen&gt;

&lt;HideOEMRegistrationScreen&gt;true&lt;/HideOEMRegistrationScreen&gt;

&lt;HideOnlineAccountScreens&gt;true&lt;/HideOnlineAccountScreens&gt;

&lt;HideWirelessSetupInOOBE&gt;true&lt;/HideWirelessSetupInOOBE&gt;

&lt;ProtectYourPC&gt;1&lt;/ProtectYourPC&gt;

&lt;SkipMachineOOBE&gt;false&lt;/SkipMachineOOBE&gt;

&lt;SkipUserOOBE&gt;true&lt;/SkipUserOOBE&gt;

&lt;/OOBE&gt;

&lt;/component&gt;

&lt;/settings&gt;

&lt;cpi:offlineImage xmlns:cpi="urn:schemas-microsoft-com:cpi" cpi:source="wim:e:/sources/install.wim#Windows 10 Pro"/&gt;

&lt;/unattend&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee107fd5-8dbb-e232-ff36-2979904e97bb
* Version Independent ID: f1c14ddf-265f-8cf0-864f-338ee8b2b2ea
* Content: [HideOEMRegistrationScreen](https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-shell-setup-oobe-hideoemregistrationscreen)
* Content Source: [customize/desktop/unattend/microsoft-windows-shell-setup-oobe-hideoemregistrationscreen.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/customize/desktop/unattend/microsoft-windows-shell-setup-oobe-hideoemregistrationscreen.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by kpacquer** [comment]
If these screens are still appearing:
* Try adding locale settings to your Unattend file (Microsoft-Windows-International-Core settings: InputLocale, SystemLocale, UILanguage, and UserLocale.)
* Check your processor architecture - it's listed here as wow64.

If neither of these work, try contacting Microsoft Support (https://support.microsoft.com/en-us/contactus/), or posting in our Forum (https://social.technet.microsoft.com/Forums/windows/en-US/home?forum=win10itprogeneral).

**Comment by dawnwood** [comment]
Hi @letme0ut Are you still having this issue?
