### ISSUE TITLE
Can this be used for a 1607 to 1803 upgrade?

### ISSUE THREAD

**Issue by curtmgray** [MicrosoftDocs/commercialization-public#217]
At the beginning of the document, it says that this is beginning with 1803. Does that mean that we can use it for an upgrade to 1803 or only on upgrades after 1803?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96747c1d-f36b-10b2-6c5f-a4bd4892a1b4
* Version Independent ID: 881dc229-bc65-bb96-d162-9edd1084b1be
* Content: [Run custom actions during a feature update](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-enable-custom-actions)
* Content Source: [manufacture/desktop/windows-setup-enable-custom-actions.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/windows-setup-enable-custom-actions.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
Hi @curtmgray - Thanks for your question. This feature can be used when upgrading to Windows 10, version 1803. Upgrading from 1607 -> 1803 should work.

**Comment by curtmgray** [comment]
Is there any reason that the GUID needs to be a big mess of alphanumeric characters or can we use some other unique folder name like 1803Update instead?
