### ISSUE TITLE
Cannot build test image due to no admin rights?!

### ISSUE THREAD

**Issue by MayMih** [MicrosoftDocs/commercialization-public#218]
When I call from Elevated Command Prompt: 
`buildimage ProductA test`
I got this error:
`Creating Productb test Image, see C:\IoT-ADK-AddonKit\Build\arm\Productb_test.log for progress
ThreadId25052 ERROR: Please run imageapp.exe in an elevated console.`
Anyone knows how to resolve this?

**Comment by dawnwood** [comment]
Hi @MayMih Apologies for the delayed response. Are you still having this issue?
Thanks,
Dawn

**Comment by saraclay** [comment]
#please-close
