### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by chesse20** [MicrosoftDocs/commercialization-public#220]
theres a glitch

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80562ce6-7e33-0c14-b88c-b9ed59673c88
* Version Independent ID: e2572f0e-89aa-596d-3b24-e200a46020b7
* Content: [Secure boot](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-secure-boot)
* Content Source: [design/device-experiences/OEM-secure-boot.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/design/device-experiences/OEM-secure-boot.md)
* Product: **windows-hardware**
* GitHub Login: @DawnWood
* Microsoft Alias: **justinha**

**Comment by themar-msft** [comment]
Hi @chesse20 - What's not working? Are you able to see the page? Or are you having an issue with Secure Boot?

**Comment by chesse20** [comment]
it wont work

**Comment by themar-msft** [comment]
I'm sorry to hear it won't work.

**Comment by dawnwood** [comment]
Hi @chesse20 Due to the length of time it's been since you opened this issue, I am assuming that your problem is resolved. 
Please reopen if you are still experiencing issues.
