### ISSUE TITLE
CreatePartitions-UEFI.txt results in extra MSR partition

### ISSUE THREAD

**Issue by kohtala** [MicrosoftDocs/commercialization-public#227]
CreatePartitions-UEFI.txt at convert gpt step the diskpart.exe already creates a MSR partition. Should update the script and instructions what to do with this partition, as the "create partition efi size=100" will be partition 2.

Microsoft Windows [Version 10.0.17134.165]
Microsoft DiskPart version 10.0.17134.1

```
DISKPART> clean

DiskPart succeeded in cleaning the disk.

DISKPART> convert gpt

DiskPart successfully converted the selected disk to GPT format.

DISKPART> list par

  Partition ###  Type              Size     Offset
  -------------  ----------------  -------  -------
  Partition 1    Reserved            15 MB    17 KB
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56201394-c4ed-706d-a904-187fc8d9abdf
* Version Independent ID: 120d1f68-7634-89f3-cac3-e96c2d2b3105
* Content: [UEFI/GPT-based hard drive partitions](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/configure-uefigpt-based-hard-drive-partitions)
* Content Source: [manufacture/desktop/configure-uefigpt-based-hard-drive-partitions.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/configure-uefigpt-based-hard-drive-partitions.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
Hi @kohtala - I just went through the steps in WinPE, and I'm not experiencing the same behavior. Are you running the script in WinPE? When I run the `convert gpt` command in Diskpart, it's not creating a new partition:

![image](https://user-images.githubusercontent.com/33436507/42777313-7a369b34-88ee-11e8-80bb-6c166af6346c.png)

**Comment by kohtala** [comment]
I created the samples on Administrative Command Prompt. I believe I saw the excess partition created in WinRE, but can not be sure.

I really was not expecting there to be this kind of difference. I thought the instruction to boot to PE was just what you'd normally do when you deploy to empty disk without OS or Win RE, but that it was not a requirement for it to create the partitions. I think if OS or Win RE require different script, it is something that deserves a mention.

**Comment by themar-msft** [comment]
Hi @kohtala - I was able to reproduce the behavior you're seeing. I looked into it, and this is expected. The MSR doesn't automatically get created when using Diskpart in WinPE, but it does when you're booted into Windows. I'll try to clarify that the script sample that we have is specific to WinPE, and won't work as-is if you're working in Windows 10.

Thanks for bringing this up!
