### ISSUE TITLE
Step 2, document and template

### ISSUE THREAD

**Issue by JinZhuXing** [MicrosoftDocs/commercialization-public#228]
Documents for the requirements and template can be found within the Fingerprint partner package on Connect.
How can I get documents for requirements and template?
Please give me a URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca2931ca-e5ca-c610-ba81-be714ee50048
* Version Independent ID: 34a04c03-bee4-feb6-6581-f4202f19badb
* Content: [Windows Hello fingerprint driver signature process](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/windows-hello-driver-signing)
* Content Source: [design/device-experiences/windows-hello-driver-signing.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/design/device-experiences/windows-hello-driver-signing.md)
* Product: **windows-hardware**
* GitHub Login: @Joshua Baxter
* Microsoft Alias: **dawnwood**

**Comment by dawnwood** [comment]
Hi @JinZhuXing Apologies for the delayed response. Are you still having this issue? The fingerprint partner package is only available to Microsoft partners. If your company is a Microsoft partner, contact your Microsoft representative to get access to the download process. 
Thanks,
Dawn

**Comment by JinZhuXing** [comment]
Thanks for your response. How can I make our company as Microsoft partner?

**Comment by dawnwood** [comment]
Hi @JinZhuXing Here's a resource that will help. https://partner.microsoft.com/en-US/
Thanks,
Dawn
