### ISSUE TITLE
Wrong instructions

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/commercialization-public#229]
Copying "Microsoft-Windows-Client-Language-Pack_x64_fr-fr.cab" inside \LangPacks folder as described is not detected by Get-Intl, hence not added to lang.ini.
Instead, create a subfolder per language, and name CAB as "lp.cab", as follows:
\LangPacks\fr-FR\lp.cab
\LangPacks\es-ES\lp.cab
\LangPacks\pt-PT\lp.cab

Additional subfolder levels are not managed properly, i.e. \LangPacks\pt-PT\subfolder\lp.cab

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad19326e-f72b-22b4-9646-7c004f4789ea
* Version Independent ID: 2ddd5e50-4f51-409e-758b-8c3abf36d952
* Content: [Add Multilingual Support to a Windows Distribution](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/add-multilingual-support-to-a-windows-distribution#feedback)
* Content Source: [manufacture/desktop/add-multilingual-support-to-a-windows-distribution.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/add-multilingual-support-to-a-windows-distribution.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by dawnwood** [comment]
Hi @juanand Apologies for the delayed response. Are you still having this issue? This sounds like feedback for the engineering team. Your feedback is better submitted in the Feedback Hub, that you can find by typing "Feedback Hub" in the Start menu.
Thanks,
Dawn
