### ISSUE TITLE
Kernel is missing or contains errors

### ISSUE THREAD

**Issue by Tom-Evers** [MicrosoftDocs/commercialization-public#231]
I've followed all the steps to the letter, and still:
After running ApplyImage and rebooting, I get a bluescreen, telling me to repair my device because the operating system cannot be loaded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7caff52b-314d-a2a5-8d19-318784f04d3b
* Version Independent ID: e35e1a40-b875-cef7-8e15-a8f18f01c46a
* Content: [Lab 2: Deploy Windows using a script](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/deploy-windows-with-a-script-sxs)
* Content Source: [manufacture/desktop/deploy-windows-with-a-script-sxs.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/deploy-windows-with-a-script-sxs.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by kpacquer** [comment]
I'm sorry you're having issues with the script. Note, Compact OS is supported for Windows 10, but not for previous versions of Windows.) If you need help, I recommend contacting Microsoft Support (https://support.microsoft.com/contactus ), or you can post in the Forum (https://social.technet.microsoft.com/Forums/windows/home?forum=win10itprogeneral ).
