### ISSUE TITLE
Isn't the value for <other> calculations for Windows 8 scaling mode incorrect?

### ISSUE THREAD

**Issue by joshgentry** [MicrosoftDocs/commercialization-public#235]
Shouldn't the formula be:
	"&lt;other&gt; * 96 / 100  scaling on every display"

Rather than the existing:
	"&lt;other&gt;*100/96 scaling on every display"

From the pre-defined values, the 96 / 100 formula works out, the other formula produces odd (non-integral) values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 969f21a8-76ad-564a-eecf-b81b3eb7984d
* Version Independent ID: f683a090-4ba1-14a5-db8a-fc697bd7aaf7
* Content: [DPI-related APIs and registry settings](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dpi-related-apis-and-registry-settings#span-idsystemspanspan-idsystemspansystem-wide-scale-factor-in-windows-8-scaling-mode)
* Content Source: [manufacture/desktop/dpi-related-apis-and-registry-settings.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/dpi-related-apis-and-registry-settings.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by QuinnRadich** [comment]
Thanks for the heads-up - I think you're correct, but I'll check in with the feature team to confirm, and then go forward with necessary changes.

**Comment by dawnwood** [comment]
@QuinnRadich What did you find out about this topic? Can you update us?
Thanks!

**Comment by QuinnRadich** [comment]
Yes, apologies.

The issue is correct - formula should be changed to 96 / 100.

**Comment by dawnwood** [comment]
The topic should be updated now. Thanks for noticing this mistake.
Best,
Dawn
