### ISSUE TITLE
Does this work for feature updates?

### ISSUE THREAD

**Issue by curtmgray** [MicrosoftDocs/commercialization-public#237]
Does this work when running a feature update to Windows 10, for example going from 1607 to 1803?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccb229f6-70fe-c94a-d853-1138da4f1853
* Version Independent ID: 7b184f62-90dd-e57f-b1fc-7eda30001796
* Content: [Add a Custom Script to Windows Setup](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/add-a-custom-script-to-windows-setup)
* Content Source: [manufacture/desktop/add-a-custom-script-to-windows-setup.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/add-a-custom-script-to-windows-setup.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by dawnwood** [comment]
Hi! I'm going to close this doc issue but please let us know if you are still having issues.
Best,
Dawn
