### ISSUE TITLE
XPS Viewer for WIndows 10 v1803

### ISSUE THREAD

**Issue by mchild** [MicrosoftDocs/commercialization-public#240]
I am not able to install XPS Viewer; My Computer is an WSUS client and there are currently no available packages for XPS view for 1803 on WSUS.  You should add this to the WSUS, or update catalog so Admins can make this available, or add to Store for Business. I also have around 150 systems that are not internet connected that I need to be able to install this "optional feature" on, and there is NO WAY to get this legitimately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1b4314-2f33-6077-64c4-4bd738311d5a
* Version Independent ID: c24e32d4-51bc-bb0f-bdff-91dbde38d585
* Content: [Features On Demand](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/features-on-demand-v2--capabilities)
* Content Source: [manufacture/desktop/features-on-demand-v2--capabilities.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/features-on-demand-v2--capabilities.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by MPC1961** [comment]
Hi, did you ever solve this issue with installing XPS Viewer on systems not connected to the internet?  I have the same problem.

**Comment by mchild** [comment]
Nope, never did.  I thought they would eventually release the feature on demand cabs for WSUS; but there I go thinking again.  what's worse is that I tried to grab the cabs from the update download folder of a network connected computer, but that is either not possible, or I'm not that smart.
________________________________

**Comment by MPC1961** [comment]
Thanks for the feedback.
If I get a solution I will let you know.

*Mark*

**Comment by JBWH** [comment]
I was able to kind of work around this; total kludge, but whatever works...

Watching the %windir%\cbstemp folder on an unmanaged 1803 box while the XPS Viewer was installing, you'll see a folder get created named "bunchOfNumbers_Morenumbers" with a subdir named FodWU.
Inside that FodWU folder, all of the necessary files will show up towards the end of the installation process.  They'll then get deleted automatically.  If you can copy them out fast enough to some other location, they're at least usable with dism.  I have not tried getting them into WSUS.
