### ISSUE TITLE
Samples for the examples

### ISSUE THREAD

**Issue by donno** [MicrosoftDocs/commercialization-public#241]
One of the examples is for instrumenting "Begin/End of significant operations".
Would it be possible to link this example to a sample/guide on how to accomplish this?
If no such example could one be written/added.  As well as a screenshot of how it expected to look in Windows Performance Analyzer tool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ff2b966-e4fd-e34d-88b6-db1c59292041
* Version Independent ID: aaafc294-65f8-00be-5ba6-b1687afed89e
* Content: [Instrumenting Your Code with ETW](https://docs.microsoft.com/en-us/windows-hardware/test/weg/instrumenting-your-code-with-etw)
* Content Source: [test/weg/instrumenting-your-code-with-etw.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/test/weg/instrumenting-your-code-with-etw.md)
* Product: **windows-hardware**
* GitHub Login: @Joshua Baxter
* Microsoft Alias: **eliotgra**

**Comment by dawnwood** [comment]
Hi @donno Apologies for the delayed response and thank you for the feedback. Do you still have questions about this?

**Comment by dawnwood** [comment]
Hi @Justinha, Is this something you can help with?

**Comment by dawnwood** [comment]
Hi! Does this topic answer your question? [ETW Tracing](https://docs.microsoft.com/en-us/dotnet/framework/wcf/samples/etw-tracing). Please let us know if you still have questions.
