### ISSUE TITLE
Seems like the documentation for HLK Manager could be a little bit more than a screen shot of the home page. Of course one could bring up Help in HLK Manager, but there they'll find exactly the same thing.

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/commercialization-public#244]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d190f57-2dae-97e1-8a98-c64144a9fccb
* Version Independent ID: b6eb3d59-c9e5-f68f-a81b-fbf63e2093b3
* Content: [HLK Manager](https://docs.microsoft.com/en-us/windows-hardware/test/hlk/user/hlk-manager)
* Content Source: [test/hlk/user/hlk-manager.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/test/hlk/user/hlk-manager.md)
* Product: **windows-hardware**
* GitHub Login: @aahi
* Microsoft Alias: **aahi**

**Comment by dawnwood** [comment]
Hi @druske Apologies for the delayed response. Do you have a specific question or is this a general request for enhancing the topic? Your answer will help me route your feedback.

**Comment by druske** [comment]
This is most certainly a general request; there's just a *screen shot* of HLK Manager. That seems like a pretty big opportunity for improving the documentation. I don't recall what I was trying to look up at the time --- I think I was trying to figure out how to delete some results from the database --- but I know I would have been glad to have some guidance in using the tool.

Thanks,
Dave

**Comment by dawnwood** [comment]
Gotcha, thank you Dave. I'll pass this on to the appropriate writer.
