### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by TDHTTTT** [MicrosoftDocs/commercialization-public#245]
The entry for left super curtain width does not seem to be right (a missing type?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a4bd720-750b-0bb9-47b9-5aca2f8eef0e
* Version Independent ID: dfcc3d26-54aa-436c-a110-5e0b2ad29343
* Content: [Precision touchpad tuning](https://docs.microsoft.com/en-us/windows-hardware/design/component-guidelines/touchpad-tuning-guidelines)
* Content Source: [design/component-guidelines/touchpad-tuning-guidelines.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/design/component-guidelines/touchpad-tuning-guidelines.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **dongill**

**Comment by aahill** [comment]
Hi @TDHTTTT, thanks for letting us know about this. I've updated the topic (it was indeed a typo), and should be fixed in the next day or so!
