### ISSUE TITLE
PINLESS Bitlocker & compliance

### ISSUE THREAD

**Issue by seemagu14** [MicrosoftDocs/commercialization-public#249]
Hell! I am looking for some resources to get feedback on whether the PINLESS implementation of Bitlocker is NIST compliant. Would appreciate any supporting documentation as well. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10c23eaa-4e0e-2594-df17-76bf9c0baa29
* Version Independent ID: b4345de1-ab7a-058a-e332-da11ca84f1e8
* Content: [BitLocker Drive Encryption](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/bitlocker-drive-encryption#feedback)
* Content Source: [manufacture/desktop/bitlocker-drive-encryption.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/bitlocker-drive-encryption.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by Justinha** [comment]
@seemagu14 I've forwarded your question to an internal set of BitLocker experts but have received any reply, and I'm not clear why that policy setting would impact compliance. Is there a specific NIST standard that you are concerned about? NIST has published its own paper about BitLocker in Windows 10 here: https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp3092.pdf 

TPM only is recommended for Modern Standby devices and devices that meet HSTI.

**Comment by Justinha** [comment]
There is a BitLocker Group Policy setting that might be relevant too: https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings#fips-setting

**Comment by seemagu14** [comment]
Justin - Thank you for the information this quickly. I will review and reply back if I have any additional questions. thank you
Seema
