### ISSUE TITLE
I need to veryify HDD behavior in Modern Standby

### ISSUE THREAD

**Issue by arthas1123** [MicrosoftDocs/commercialization-public#251]
I need to know about the power consumption and load unload counts.
But first of all, how do I turn a laptop with HDD, basically not supporting MS, to supporting MS?
Could you please give me some guide?
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d753fad-5717-0d0f-21ca-9684fddeeb01
* Version Independent ID: 325292e8-8c4a-7b9a-4988-7809b8999043
* Content: [Modern Standby system behavior verification](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/modern-standby-system-behavior-verification)
* Content Source: [design/device-experiences/modern-standby-system-behavior-verification.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/design/device-experiences/modern-standby-system-behavior-verification.md)
* Product: **windows-hardware**
* GitHub Login: @Joshua Baxter
* Microsoft Alias: **dongill**

**Comment by dawnwood** [comment]
Hi @arthas1123 Apologies for the delayed response. Do you still have this question? If so, I need more details about "not supporting MS to supporting MS". What do you mean by that, specifically?

**Comment by dawnwood** [comment]
Hi again! I'm going to close this doc issue but please let us know if you still have an issue.
Best,
Dawn
