### ISSUE TITLE
Where Can I download this BootSect?

### ISSUE THREAD

**Issue by oswazteca** [MicrosoftDocs/commercialization-public#253]
I am running Windows 7 USB DVS download tool, but at the end, I get the message https://cl.ly/2942132K2v3n/Image%202018-07-26%20at%201.08.38%20PM.png I found one possible solution https://www.cduser.com/solucionar-problemas-con-bootsect-al-crear-un-usb-de-arranque-de-windows/ but I don't want to download the file he is sharing, I would like some official download.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d877b76b-53be-d412-948e-5746f20f342e
* Version Independent ID: f74630f4-f9f6-9d4a-20ca-22fc33e4aad4
* Content: [Bootsect Command-Line Options](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/bootsect-command-line-options)
* Content Source: [manufacture/desktop/bootsect-command-line-options.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/bootsect-command-line-options.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by dawnwood** [comment]
Hi @oswazteca Apologies for the delayed response. Are you still experiencing this issue?

**Comment by oswazteca** [comment]
Yeah, never figured out.

**Comment by dawnwood** [comment]
Hi @oswazteca I think the problem is that Windows 7 is no longer supported. You can see what operating systems Microsoft fully supports on this [site](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet). Hope this helps,
Dawn
