### ISSUE TITLE
Text referenced from UEFI specification, not found in spec document

### ISSUE THREAD

**Issue by milindsmart** [MicrosoftDocs/commercialization-public#259]
The Hardware Dev Center page on [UEFI Validation Option ROM Guidance](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/uefi-validation-option-rom-validation-guidance#uefiandoptionroms) seemingly quotes some Secure Boot requirement text from the UEFI 2.3.1 Errata C specification (Lines 135 and 137):

> From the UEFI 2.3.1 Eratta C specification:
>
>9. Mandatory. **Signed Firmware Code Integrity Check**. Firmware that is installed by the OEM and is either read-only or protected by a secure firmware update process, as defined above, may be considered protected. **Systems shall verify that all unprotected firmware components, UEFI drivers, and UEFI applications are sigend using minimum RSA-2048 with SHA-256 (MD5 and SHA-1 are prohibited)**, and verify that UEFI applications and drivers that are not signed as per these requirements will fail to run (this is the default policy for acceptable signature algorithms). If an images signature is not found in the authorized database, or is found in the forbidden database, the image must not be started, and instead, information about it shall be placed in the Image Execution Information Table.11. Mandatory. **Verify Signature of all Boot Apps and Boot Loaders.** Upon power-on, the platform shall start executing boot firmware and use public key cryptography as per algorithm policy to verify the signatures of all images in the boot sequence up-to and including the Windows Boot Manager.

But I just cannot find these lines in the [UEFI specification](http://www.uefi.org/sites/default/files/resources/UEFI_2_3_1_C.pdf). Can someone clarify? Are these Microsoft Hardware Test Certification requirements?

**Comment by dawnwood** [comment]
Hi @milindsmart Apologies for the delayed response. Did you get your question answered?

**Comment by dawnwood** [comment]
Hi, you are right--the text says it's from the UEFI spec when in fact it comes from the [Windows Hardware Compatibility Program](https://docs.microsoft.com/en-us/windows-hardware/design/compatibility/whcp-specifications-policies#download-compatibility-documents). I am updating the text and will let you know when that is done. Thank you for taking the time to report this.
Best,
Dawn

**Comment by dawnwood** [comment]
@milindsmart , the document is now updated in two ways: there is a section from the
Windows Hardware Compatibility Program, and a section that is a modified version of text that originally came from the spec. Both of these are now so labeled. 
Best,
Dawn
