### ISSUE TITLE
Invalid setting, the product key needs to be set in the actual operation.

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/commercialization-public#264]
Invalid setting, the product key needs to be set in the actual operation.
![snipaste_2018-08-01_09-04-02](https://user-images.githubusercontent.com/14959656/43495492-fec706d0-956a-11e8-8906-418f1201052e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61d1a67f-f1c0-5d53-e492-5ecb6ddfb42b
* Version Independent ID: 69609f13-5e70-4e20-99bb-6a6b317f1a78
* Content: [SKUPolicyRequired](https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-codeintegrity-skupolicyrequired)
* Content Source: [customize/desktop/unattend/microsoft-windows-codeintegrity-skupolicyrequired.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/customize/desktop/unattend/microsoft-windows-codeintegrity-skupolicyrequired.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by dawnwood** [comment]
Hi @goxia Apologies for the delayed response. Are you still having this issue? This sounds like feedback for the engineering team. Your feedback is better submitted by clicking the "product feedback" button at the bottom of every topic on docs.microsoft.com
Thanks,
Dawn

**Comment by goxia** [comment]
Hi @dawnwood , Thank you. I will consider feedback to the product group.
