### ISSUE TITLE
Microsoft Lumia 950 XL Dual SIM Version 10.0.15254.490.

### ISSUE THREAD

**Issue by pavlaras1** [MicrosoftDocs/commercialization-public#269]
Microsoft Lumia 950 XL Dual SIM Version 10.0.15254.490.
Almost None of all those codes work to my phone.
Only the Reset Phone Code work and the Total Timer and Color Codes Work.
Please check it and fix the codes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0459f65a-e8e7-9fa2-b25b-7fa649540683
* Version Independent ID: 43e20b0f-be3a-9ec6-334f-7ad1d63d24e8
* Content: [Dialer codes to launch diagnostic applications](https://docs.microsoft.com/en-us/windows-hardware/customize/mobile/mcsf/dialer-codes-to-launch-diagnostic-applications)
* Content Source: [customize/mobile/mcsf/dialer-codes-to-launch-diagnostic-applications.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/customize/mobile/mcsf/dialer-codes-to-launch-diagnostic-applications.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by themar-msft** [comment]
Hi @pavlaras1 - Are you building an image for your 950XL? Or are you trying to use the dialer codes on your device?

**Comment by pavlaras1** [comment]
I am just trying to use the dialer codes on my device.

**Comment by themar-msft** [comment]
This topic covers possibilities that manufacturers can do with dialer codes. Not all dialer codes that are mentioned in this topic applies to all devices. It's up to the manufacturer to include support for the different dialer codes.

So, it could be that your device only supports the codes that you mention.
