### ISSUE TITLE
Legal Agreement for Attested IHV  signing service.

### ISSUE THREAD

**Issue by vipinsinghai44** [MicrosoftDocs/commercialization-public#271]
What are the legal agreement to be signed for Attested IHV signing service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce0fab07-0bc3-b98a-6790-f589cd6c131b
* Version Independent ID: 4b4de23a-37b8-d060-c475-6a8232ced565
* Content: [IHV Attested Signing Service](https://docs.microsoft.com/en-us/windows-hardware/design/compatibility/ihv-attested-signing-service)
* Content Source: [design/compatibility/ihv-attested-signing-service.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/design/compatibility/ihv-attested-signing-service.md)
* Product: **windows-hardware**
* GitHub Login: @sapaetsc
* Microsoft Alias: **sapaetsc**

**Comment by dawnwood** [comment]
Hi @vipinsinghai44 Apologies for the late reply. Do you still have this question?

**Comment by vipinsinghai44** [comment]
Yes

**Comment by dawnwood** [comment]
Ok, I will check into this.

**Comment by dawnwood** [comment]
Hi again, @vipinsinghai44 Here's a link that should answer your question. Please let us know if that doesn't help.
Best,
Dawn

**Comment by dawnwood** [comment]
https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/attestation-signing-a-kernel-driver-for-public-release
