### ISSUE TITLE
Merge contents of other page

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/commercialization-public#272]
I think this page should be updated with details from https://docs.microsoft.com/en-us/windows/configuration/customize-and-export-start-layout

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23ad2d2c-8e5f-8dd0-079f-cfd50f1c15cb
* Version Independent ID: f9b85fa9-d56a-f1c4-6f1f-0eda321885f9
* Content: [Customize the Start layout](https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/customize-start-layout)
* Content Source: [customize/desktop/customize-start-layout.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/customize/desktop/customize-start-layout.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by themar-msft** [comment]
Hi @hoyty76 - Thanks for the suggestion! These topics, even though they cover similar things, are for different audiences (one topic is for OEMs, and one is for IT Pros). I'll take a look and see if there's anything that should be added to this topic though.
