### ISSUE TITLE
Using wevtutil im with a kernel driver

### ISSUE THREAD

**Issue by jcbottorff** [MicrosoftDocs/commercialization-public#273]
I have event tracing in a kernel driver, and when I try to install the manifest using wevtutil im, with the message/resource paths pointing into the "%SystemDrive%\ETWDriverSample\myDriver.sys" file (as per the kernel example), it gets an access error. I assume this is because the OS has the driver binary locked, or permission from an admin user mode context are insufficient to access the driver file directory. For development, I can just make the manifest point at a copy of the driver binary in like c:\temp\mydriver.sys, but for production deployment, it seems like it needs to point to the real driver binary location. Is there some way to get the event manifest installed automatically with a driver install, either though some .inf registry values, or like WMI mof files get installed by being a resource in the binary. I really like ETW tracing for drivers, but the manual installation of the manifest has always been an issue. One detail is I'm using the TraceLogging APIs, where events are self-describing, so the manifest does not contain event definitions, but does contain provider/channel/keyword definitions. The end goal is when my driver is installed, by the normal PnP methods, for my event logs to show up in event viewer under Applications and Service logs, just like all the standard MSFT providers. This all works, if I manually run wevtutil im with a temp path to the binary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ff2b966-e4fd-e34d-88b6-db1c59292041
* Version Independent ID: aaafc294-65f8-00be-5ba6-b1687afed89e
* Content: [Instrumenting Your Code with ETW](https://docs.microsoft.com/en-us/windows-hardware/test/weg/instrumenting-your-code-with-etw)
* Content Source: [test/weg/instrumenting-your-code-with-etw.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/test/weg/instrumenting-your-code-with-etw.md)
* Product: **windows-hardware**
* GitHub Login: @Joshua Baxter
* Microsoft Alias: **eliotgra**

**Comment by dawnwood** [comment]
Hi @jcbottorff Thank you for the detailed feedback. This sounds like feedback about event tracing, not about the help topic. You should provide this feedback to the engineering team by clicking the "Product Feedback" button at the bottom of the pages on docs.microsoft.com. If I am misunderstanding your feedback, let me know and I'll reopen this issue.
