### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by myxal** [MicrosoftDocs/commercialization-public#275]
&gt; 3. Install Windows on the reference computer, and perform all updates that are described in the "Common Sysprep Scenarios" section of the Sysprep (System Preparation) Overview topic.

There's no such section in the linked article, nor is there anything that looks like a list of updates. Where can I find a list of these "updates"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d566ecb-54a4-2ebf-cea6-68244db59173
* Version Independent ID: 70924974-7952-0a92-b3f2-a8b13039ce41
* Content: [Configure a Trusted Image Identifier for Windows Defender](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/configure-a-trusted-image-identifier-for-windows-defender)
* Content Source: [manufacture/desktop/configure-a-trusted-image-identifier-for-windows-defender.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/configure-a-trusted-image-identifier-for-windows-defender.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by kpacquer** [comment]
Thanks Myxal! We’re updating the guidance:

1. Create a Windows Setup answer file (unattend.xml), and add the `Security-Malware-Windows-Defender\TrustedImageIdentifier` setting. To learn more, see the OEM deployment lab: [Customize Windows with an answer file](https://docs.microsoft.com/windows-hardware/manufacture/desktop/oem-deployment-of-windows-10-for-desktop-editions#customize-windows-with-an-answer-file).

2. For the value of the `TrustedImageIdentifier` setting, specify a unique identifier, such as a GUID, for the image.

3. Strongly recommended: [apply the image to a new device, and boot it into audit mode](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/oem-deployment-of-windows-10-for-desktop-editions#deploy-your-images-to-a-new-pc), and scan the image by using Windows Defender or another scanning tool. This can help make sure that the image is safe. Recapture the image.

4. Apply the image to new devices, and deliver them to customers.

   The next time that the device starts, Windows identifies all of the files currently on the system, and skips these files during subsequent scans.
