### ISSUE TITLE
That /export option is pretty much useless

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/commercialization-public#278]
What was wrong with emitting a consistently ordered human readable file?

Between this and the painfully small, non expandable UI, how is anyone supposed to troubleshoot differences or issues in configurations?  By having to take a dozen or more screenshots and eyeballing them. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b913eb5b-f713-4303-1b96-622c8c9ba51c
* Version Independent ID: 5e2ee624-b963-56ba-0e15-35590f391214
* Content: [Powercfg command-line options](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/powercfg-command-line-options)
* Content Source: [design/device-experiences/powercfg-command-line-options.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/design/device-experiences/powercfg-command-line-options.md)
* Product: **windows-hardware**
* GitHub Login: @Joshua Baxter
* Microsoft Alias: **dongill**

**Comment by dawnwood** [comment]
Hi @StingyJack Thank you for your feedback. This sounds like feedback about the command line error strings, not about the documentation. You'll get better results by providing feedback to the engineering team by clicking the "Product Feedback" button at the bottom of the page on docs.microsoft.com.
Let me know if I'm misunderstanding your feedback, and I will re-open this issue.

**Comment by StingyJack** [comment]
Hi @dawnwood, you are probably correct about it being a program that seems pointless more than about the documentation having an issue. From the outside, its usually hard to distinguish between the two. 

I dont actually see any buttons at the bottom of the page listed as "Content" in the details section above.

**Comment by dawnwood** [comment]
Hi @StingyJack Another couple of options for you are to post your question/feedback in the [product forum](https://social.msdn.microsoft.com/Forums/windowshardware/en-us/home), or by typing "Feedback Hub" into the Start menu and adding your comments there. 
And thanks for pointing out that this topic doesn't have the feedback buttons. I'll work on getting those added.
Best,
Dawn

**Comment by StingyJack** [comment]
The Windows Feedback Hub? Where the complaints about the default news presented to people gets the most votes, and actual windows issues get swallowed by that nonsense?  Or the MS/MSDN forums where requests stay unanswered until they are auto locked forever?  Thanks, but I'll have to pass on those for stress/medical/mental health reasons. =P

**Comment by dawnwood** [comment]
I am forwarding your request to the lead PM for Modern Standby. Believe it or not, feature teams KEENLY sort through Feedback Hub. It’s part of the Windows QA process, and our teams do take action based on that feedback.
