### ISSUE TITLE
Split .swm files

### ISSUE THREAD

**Issue by steve6375** [MicrosoftDocs/commercialization-public#280]
Option 4 says 'Windows Setup doesn't support installing from a split .wim file for Windows 10.'

but on other pages it says it works! It has also worked for me on many occasions. So is this correct?

See
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/install-windows-from-a-usb-flash-drive

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ccfc818-492e-94d9-e10c-bcd91ad78e63
* Version Independent ID: a5d6f3ec-51d7-1753-2259-150638d56ce0
* Content: [WinPE: Store or split images to deploy Windows using a single USB drive](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe--use-a-single-usb-key-for-winpe-and-a-wim-file---wim)
* Content Source: [manufacture/desktop/winpe--use-a-single-usb-key-for-winpe-and-a-wim-file---wim.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/winpe--use-a-single-usb-key-for-winpe-and-a-wim-file---wim.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by kpacquer** [comment]
Thanks Steve! You're right, we're updating the guidance in this topic:

> Applying split image (.swm) files is only supported when all of the .swm files are in the same folder, as shown in these steps.

Note, we used to also recommend splitting WIMs for a DVD-based installation. Windows Setup would prompt for each new DVD using a set of .swm files. But, we found it doesn't always work with Windows 10. So, we created a workaround: [Split a Windows image file (.wim) to span across multiple DVDs](https://docs.microsoft.com/windows-hardware/manufacture/desktop/split-a-windows-image--wim--file-to-span-across-multiple-dvds).

**Comment by kpacquer** [comment]
Thanks Steve! You're right, the steps in this topic should work just fine. We're updating the guidance:

> Applying split image (.swm) files is only supported when all of the .swm files are in the same folder, as shown in these steps.

On a separate note, we used to also recommend splitting WIMs for a DVD-based installation. Windows Setup would prompt for each new DVD using a set of .swm files. But, we found it doesn't always work with Windows 10. So, we created a workaround: [Split a Windows image file (.wim) to span across multiple DVDs](https://docs.microsoft.com/windows-hardware/manufacture/desktop/split-a-windows-image--wim--file-to-span-across-multiple-dvds).

**Comment by kpacquer** [comment]
Thanks Steve! You're right, the steps in this topic should work just fine. We're updating the guidance:

> Applying split image (.swm) files is only supported when all of the .swm files are in the same folder, as shown in these steps.

On a related note, most of the problems we see with split WIMs happen when using Windows Setup across multiple DVDs or multiple USB keys. It still works, sometimes, but there's some known issues. The more reliable method in these situations is to [copy everything to a single folder on the destination PC before applying the image](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/split-a-windows-image--wim--file-to-span-across-multiple-dvds#dvd-deployment).
