### ISSUE TITLE
anchors

### ISSUE THREAD

**Issue by itizotope** [MicrosoftDocs/commercialization-public#281]
The anchor IDs are pretty weird, e.g. "#span-idimageoptimizationspanspan-idimageoptimizationspanspan-idimageoptimizationspanimage-optimization"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9b960ec-90d5-e36c-f650-1296958b1e5a
* Version Independent ID: a69c63ba-60e8-23aa-b1bb-695cfb24c531
* Content: [Compact OS, single-instancing, and image optimization](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/compact-os#span-idimageoptimizationspanspan-idimageoptimizationspanspan-idimageoptimizationspanimage-optimization)
* Content Source: [manufacture/desktop/compact-os.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/compact-os.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by dawnwood** [comment]
Hi @itizotope Do the anchor ids work for you, or are they broken?

**Comment by itizotope** [comment]
Hello Dawn,

Thank you for checking in. The team member who initially submitted this
issue via GitHub is no longer with the team, and we are unable to discern
what it was referencing. Feel free to close this one out.

Thank you,

iZotope IT

**Comment by owenmann** [comment]
They work, they're just ridiculous.

**Comment by dawnwood** [comment]
@itizotope , thank you I will do that. @owenmann They're autogenerated so we'll have to leave them as they are.
