### ISSUE TITLE
Capture Config_AppsAndSettings issue

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/commercialization-public#286]
I did this using the command line below, but found that the application was successfully restored, but the system settings did not take effect.

`E:\ADKTools\ScanState.exe /apps:+sysdrive /o /v:13 /config:E:\ADKTools\Config_AppsAndSettings.xml /ppkg e:\SPPs\FullBase.spp /l:e:\adktools\scanstate.log`

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 83ab62fa-dc8c-8765-fbbd-b365908601cc
* Version Independent ID: 17d3469e-c596-a3e4-9fc5-7d005fb45ee0
* Content: [Siloed provisioning packages](https://docs.microsoft.com/zh-cn/windows-hardware/manufacture/desktop/siloed-provisioning-packages)
* Content Source: [manufacture/desktop/siloed-provisioning-packages.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/siloed-provisioning-packages.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by dawnwood** [comment]
Hi @goxia Are you still experiencing this issue?

**Comment by goxia** [comment]
Hi @dawnwood , Thank you.
Since there is no exhaustive documentation on what the system settings contain, Perhaps my issue has been resolved.
