### ISSUE TITLE
Windows 10 Pro for Workstations

### ISSUE THREAD

**Issue by DHOEMSpecialist** [MicrosoftDocs/commercialization-public#287]
There's no differentiation for Windows 10 Pro for Workstations being the only approved Client OS for systems with Xeon processors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8432784f-823e-a622-73ef-f5c57188fe9e
* Version Independent ID: 4b86983c-eac5-7725-8add-fa174248ea5e
* Content: [Windows Processor Requirements](https://docs.microsoft.com/en-us/windows-hardware/design/minimum/windows-processor-requirements)
* Content Source: [design/minimum/windows-processor-requirements.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/design/minimum/windows-processor-requirements.md)
* Product: **windows-hardware**
* GitHub Login: @Andy Kovar
* Microsoft Alias: **dongill**

**Comment by greg-ashby** [comment]
Hi, I'm currently trying to clarify this as well. We are looking at procuring a couple Xeon workstations and can't confirm if our corporate image will be compatible. We have enterprise licensing and my understanding is Windows 10 Pro for Workstations is the basis for Windows 10 Enterprise, so it _should_ be ok. But this page lists 1803 as only supporting for "up to" 7th Gen Xeon, where as latest Xeon version is 8th Gen.

I assume this page just hasn't been updated yet, but I'm hesitant to proceed with an order without being able to confirm that.

**Comment by dcasanares** [comment]
What do you mean by Windows 10 Pro for Workstation is the basis for Windows 10 Enterprise?

**Comment by DHOEMSpecialist** [comment]
I heard that Windows 10 Enterprise provides all the features of Windows 10 Pro for Workstations but is not a licensing substitute. It's my understanding that a Windows 10 Pro for Workstations base license is required.

**Comment by themar-msft** [comment]
Hi @greg-ashby , @dcasanares , and @DHOEMSpecialist - This topic has been updated to include notes about Xeon processors, as well as Windows 10, version 1809.

**Comment by greg-ashby** [comment]
Thanks for the update @themar-msft
