### ISSUE TITLE
Not enough information for disabling express settings

### ISSUE THREAD

**Issue by ciphernemo** [MicrosoftDocs/commercialization-public#296]
No additional information about disabling express settings with value '3' and then choosing with items to enable or disable. A link to an article about this or more information about express settings would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 773f0905-f50b-092f-f93b-02c3c965a8f0
* Version Independent ID: 1f9e0ed4-d994-abb9-bcda-003a2d14da0e
* Content: [ProtectYourPC](https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-shell-setup-oobe-protectyourpc)
* Content Source: [customize/desktop/unattend/microsoft-windows-shell-setup-oobe-protectyourpc.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/customize/desktop/unattend/microsoft-windows-shell-setup-oobe-protectyourpc.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by kpacquer** [comment]
Thanks Ciphernemo, we're adding a See Also link to [Automate OOBE](https://docs.microsoft.com/windows-hardware/customize/desktop/automate-oobe) to this topic and the other settings listed on the Automate OOBE page.
