### ISSUE TITLE
copype is not correct anymore

### ISSUE THREAD

**Issue by cobbjb** [MicrosoftDocs/commercialization-public#297]
"copype.cmd" should be what is documented.  I spent several minutes using just "copype" before searching for the reason "copype" wasn't working and finding this information elsewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 940c91fb-34f2-b446-b169-a98c4ec82e18
* Version Independent ID: 72dee9eb-613c-5afe-4eed-2cd6d5cb2dad
* Content: [WinPE: Create bootable media](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-create-usb-bootable-drive)
* Content Source: [manufacture/desktop/winpe-create-usb-bootable-drive.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/winpe-create-usb-bootable-drive.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
Hi @cobbjb - copype should work if you're running the command from the Deployment and Imaging Tools Environment. Were you trying to run copype from a regular Command Prompt or the Deployment and Imaging Tools Environment?
