### ISSUE TITLE
1

### ISSUE THREAD

**Issue by U5Alekseevich** [MicrosoftDocs/commercialization-public#298]
[Введите отзыв здесь]

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 78a7ade4-09ab-e0b2-4ace-a14b2d9c9bce
* Version Independent ID: 34de1342-2814-e81f-0f72-25395d07d6a6
* Content: [Download and install the Windows ADK](https://docs.microsoft.com/ru-ru/windows-hardware/get-started/adk-install)
* Content Source: [get-started/adk-install.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/get-started/adk-install.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by EliotSeattle** [comment]
No issue listed.
