### ISSUE TITLE
I can not offline install at version1803.

### ISSUE THREAD

**Issue by AkiraUemura** [MicrosoftDocs/commercialization-public#302]
Although installation to the test server was carried out according to the following procedure, installation is impossible because connection to the network is requested at the time of installation.

&gt; If you choose the download option, copy your download to your test server.
&gt; Run HLKSetup.exe and repeat the installation instructions from Step 3 for installing to this computer.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: bbe54537-bd66-c344-0cd5-250a91d4e4bd
* Version Independent ID: 67abec87-2b38-da6b-7bb8-042fdef4d0fc
* Content: [Step 1 Install Controller and Studio on the test server](https://docs.microsoft.com/ja-jp/windows-hardware/test/hlk/getstarted/step-1-install-controller-and-studio-on-the-test-server)
* Content Source: [test/hlk/getstarted/step-1-install-controller-and-studio-on-the-test-server.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/test/hlk/getstarted/step-1-install-controller-and-studio-on-the-test-server.md)
* Product: **windows-hardware**
* GitHub Login: @aahi
* Microsoft Alias: **aahi**

**Comment by dawnwood** [comment]
Hello @AkiraUemura You are right, you need a connection to the internet in order to download the files. Does that answer your question?

**Comment by dawnwood** [comment]
Hi @AkiraUemura I'm closing this doc issue but please let us know if you have other questions or feedback.
Best,
Dawn

**Comment by AkiraUemura** [comment]
Hi @dawnwood
Thank you for your support.
I successfully installed it as a result of re-downloading HLK.

Best Regards,
Akira

**Comment by dawnwood** [comment]
Yay! Thanks for letting us know.
