### ISSUE TITLE
 Workflow steps for WSSD validation with PCS

### ISSUE THREAD

**Issue by r936310** [MicrosoftDocs/commercialization-public#305]
the content in Workflow steps for WSSD validation with PCS &lt;https://docs.microsoft.com/en-us/windows-hardware/test/hlk/testref/partner-guide-to-wssd-certification#span-idworkflowstepsforwssdvalidationwithpcsspanspan-idworkflowstepsforwssdvalidationwithpcsspanspan-idworkflowstepsforwssdvalidationwithpcsspanworkflow-steps-for-wssd-validation-with-pcs&gt; is confusing without paragraph and hard to understand. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e4ecdcc-e3e0-5865-78ef-5ff08f9271b3
* Version Independent ID: 3530d3b2-3a4b-c32f-2469-3a1a81aedb77
* Content: [Partner Guide to WSSD Certification](https://docs.microsoft.com/en-us/windows-hardware/test/hlk/testref/partner-guide-to-wssd-certification#feedback)
* Content Source: [test/hlk/testref/partner-guide-to-wssd-certification.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/test/hlk/testref/partner-guide-to-wssd-certification.md)
* Product: **windows-hardware**
* GitHub Login: @aahi
* Microsoft Alias: **aahi**

**Comment by dawnwood** [comment]
Hi @r936310 You are right that looks hard to read. This topic is autogenerated; I am following up.

**Comment by dawnwood** [comment]
Hi @r936310 The page is updated now, the confusing (and wrong) sections are removed. 
Best,
Dawn
