### ISSUE TITLE
Script Errors Found

### ISSUE THREAD

**Issue by ehendricks** [MicrosoftDocs/commercialization-public#307]
Found two errors in this script:
1. Line 44 - Write-Error message not enclosed in quotes
2. Line 123 - "Ctrl+Alt+Delete" is not a valid predefined key - Should be "Ctrl+Alt+Del"

Thanks,

Eric S. Hendricks
eric@erics-web.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3a9d83b-df25-06e2-6cc1-aa5cacced539
* Version Independent ID: 7626cc7d-14f2-cf57-18ae-4660fdb7f9f2
* Content: [Add blocked key combinations](https://docs.microsoft.com/en-us/windows-hardware/customize/enterprise/keyboardfilter-add-blocked-key-combinations)
* Content Source: [customize/enterprise/keyboardfilter-add-blocked-key-combinations.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/customize/enterprise/keyboardfilter-add-blocked-key-combinations.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by kpacquer** [comment]
Thanks @ehendricks ! We've fixed the errors in the scripts.
