### ISSUE TITLE
misinformation

### ISSUE THREAD

**Issue by angryuser4** [MicrosoftDocs/commercialization-public#309]
Your recommendation to have the recovery partition after the windows partition is impossible. It is the first partition and we're not given choice on moving it which contradicts your recommendation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56201394-c4ed-706d-a904-187fc8d9abdf
* Version Independent ID: 120d1f68-7634-89f3-cac3-e96c2d2b3105
* Content: [UEFI/GPT-based hard drive partitions](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/configure-uefigpt-based-hard-drive-partitions)
* Content Source: [manufacture/desktop/configure-uefigpt-based-hard-drive-partitions.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/configure-uefigpt-based-hard-drive-partitions.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
Hi @angryuser4 . If you use the sample partitioning scripts we provide, the recovery partition will be placed after the Windows partition.
