### ISSUE TITLE
Issue - Error: 87 - MetaDeployProvider.dll - SiloedPackageProvider.dll - Fail to load provider

### ISSUE THREAD

**Issue by Gregory78400** [MicrosoftDocs/commercialization-public#310]
Hi,

1. Prerequisites:
I installed the package as admim.
I checked versions compatibility
I opened my CMD as admin
I tried on multiple versions (ADK and Windows in virtual machines and on my host).
Current Windows Build : 17134
Deployment Image Servicing and Management tool: Version: 10.0.17134.1
Package: Windows ADK for Windows 10, version 1803

2. Incident:
I have been working around this issue for two days so far. Whatever version I install (in my last attempt Windows 10 Version 1803), I still encounter this issue while I try this command to split my WIM file into several SWM files. Here the command necessary for my ISO to be compliant with FAT32.

Dism /Split-Image /ImageFile:MyFile.wim /SWMFile:FinalFile.swm /FileSize:3800

The error message:
Error: 87
The parameter is incorrect.

When checking logs here is the problem:

- Warning: Failed to load the provider: C:\WINDOWS\system32\Dism\SiloedPackageProvider.dll. - CDISMProviderStore::Internal_GetProvider(hr:0x8007007e)

- Waring: Failed to load the provider: C:\WINDOWS\system32\Dism\MetaDeployProvider.dll. - CDISMProviderStore::Internal_GetProvider(hr:0x8007007e)

MetaDeployProvider.dll is not present in my system but I have this one:
MetaDeployment.dll in C:\Program Files (x86)\Windows Kits\10\1803\Assessment and Deployment Kit\Imaging and Configuration Designer\x86

Thanks for your help.

Gregory

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78a7ade4-09ab-e0b2-4ace-a14b2d9c9bce
* Version Independent ID: 34de1342-2814-e81f-0f72-25395d07d6a6
* Content: [Download and install the Windows ADK](https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install)
* Content Source: [get-started/adk-install.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/get-started/adk-install.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by dawnwood** [comment]
Hi @Gregory78400 Apologies for the delayed response. Are you still experiencing this issue?

**Comment by themar-msft** [comment]
@Gregory78400 - See this topic about using a single USB drive to deploy an image: https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe--use-a-single-usb-key-for-winpe-and-a-wim-file---wim

Option 1 in that topic may be helpful for you. It describes creating a multipartition USB drive with two partitions - 1 FAT32 to boot to WinPE, and 1 NTFS partition that can hold a Windows image that is larger than 4GB.

If you want to run the version of DISM that comes with the ADK, launch the Deployment and Imaging Tools Command Prompt as administrator and run the command from there. It sounds like you might be trying to run DISM from a regular administrative Command Prompt.

**Comment by dawnwood** [comment]
Hi again, @Gregory78400 Did Ted's suggestion solve your issue? Or do you still need help with this?
Best,
Dawn

**Comment by Gregory78400** [comment]
Hi everyone,

It happened with a LTSB Windows 10 version ; i tried the 1703 release it perfectly worked today; great job !!!
ADK is a GREAT product!! 

Thanks for your answer.

**Themar-msft** : Don't worry I always use the elevated prompt when I work; thanks!

Gregory

**Comment by Gregory78400** [comment]
Hi team,

Caution with **Windows 10 LTSB** for those who use this kind of build; a lot of issues linked to updates in all kinds and other topics.

Gregory

**Comment by dawnwood** [comment]
Thanks, Gregory, that's great news. I will pass on your feedback to the engineering team; thank you for providing the great details above.
Best,
Dawn
