### ISSUE TITLE
Preinstalls tasks for Classic Windows Apps

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/commercialization-public#317]
Can you please provide more information on how these task types are used? That is, these look like constants. Where in the manifest, or code are these constants used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aec5769-91c6-448a-ff7c-852649f26b84
* Version Independent ID: d43f8224-d5f5-0bd0-b488-c9cfbcd2bf4c
* Content: [Preinstall tasks](https://docs.microsoft.com/en-us/windows-hardware/customize/preinstall/preinstall-tasks)
* Content Source: [customize/preinstall/preinstall-tasks.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/customize/preinstall/preinstall-tasks.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by dawnwood** [comment]
Hi @mjfusa Apologies for the late reply. Do you still have this question?

**Comment by dawnwood** [comment]
@mjfusa There are examples on this page that describe the use of the preinstall tasks. If you have a specific question after looking at the examples, please let us know.
