### ISSUE TITLE
dbghelplog is no longer a supported operation

### ISSUE THREAD

**Issue by kbuzby** [MicrosoftDocs/commercialization-public#318]
With Windows Performance Toolkit 10, running with the `-sybmbols dbghelplog` option you get the following error:  
"xperf: error: Warning: Option 'dbghelplog' is no longer supported"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d48469d-d755-1d63-9c64-1b50a02f8d56
* Version Independent ID: f3ad5d94-cf14-1343-e63a-6586401fb157
* Content: [symbols](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/symbols)
* Content Source: [test/wpt/symbols.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/test/wpt/symbols.md)
* Product: **windows-hardware**
* GitHub Login: @Joshua Baxter
* Microsoft Alias: **eliotgra**

**Comment by dawnwood** [comment]
Hi @kbuzby Apologies for the delayed response. Are you still experiencing this problem?

**Comment by kbuzby** [comment]
yes - the documentation hasn't changed: https://docs.microsoft.com/en-us/windows-hardware/test/wpt/symbols

**Comment by dawnwood** [comment]
I'm looking into this now.

**Comment by dawnwood** [comment]
The topic has been updated. Thanks again for noticing and reporting!!
Best,
Dawn
