### ISSUE TITLE
Extra space in the windbg command

### ISSUE THREAD

**Issue by rajahks** [MicrosoftDocs/commercialization-public#319]
It should be 

windbg -premote tcp:server=Server,port=1234

There should be no space after the "Server,". Having space there will cause failure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef617289-3c5c-983a-2cc1-bf1f5116aadd
* Version Independent ID: 2aae125e-3ddb-7ede-7a21-8908cb3a2f96
* Content: [WinPE: Debug Apps](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-debug-apps)
* Content Source: [manufacture/desktop/winpe-debug-apps.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/winpe-debug-apps.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by kpacquer** [comment]
Thanks @rajahks ! Fixing the example in the topic, should be live shortly.
