### ISSUE TITLE
Why is "Powercfg /h off" not valid for use in specialize phase?

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/commercialization-public#323]
I added the RunAsynchronous command to the document in the "specialize" phase, executed powercfg/h off, but the discovery did not take effect, and the check setupact.log found that the command was executed correctly, for what reason?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e9b960ec-90d5-e36c-f650-1296958b1e5a
* Version Independent ID: a69c63ba-60e8-23aa-b1bb-695cfb24c531
* Content: [Compact OS, single-instancing, and image optimization](https://docs.microsoft.com/zh-cn/windows-hardware/manufacture/desktop/compact-os#RAM)
* Content Source: [manufacture/desktop/compact-os.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/compact-os.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by kpacquer** [comment]
Hi Goxia,
You should be able to run powercfg using RunAsynchronousCommand. You might try our [hardware forum](https://social.msdn.microsoft.com/Forums/windowshardware/) to get troubleshooting help.

I did find a discussion of how to turn off hibernation during setup, including other options that might work better for you, like using MDT Task Sequences, setting the power condition in the image before capturing it, or creating your own power scheme and importing it: 

https://social.technet.microsoft.com/Forums/en-US/eb0269fc-120f-48bf-9784-c25c92798d23/turn-off-hibernation

**Comment by goxia** [comment]
yes, I am also concerned about this forum post, but it does not work from a fundamental solution to the "specialize" phase of running powercfg does not take Effect.
Currently I have found a temporary solution through the registry, thank you for your help.
