### ISSUE TITLE
Size of recovery tools partition

### ISSUE THREAD

**Issue by SamueleDecarli** [MicrosoftDocs/commercialization-public#324]
Installing Windows 10 1803 64-bit.
I followed the instructions and ended up with a 500MB recovery partition. I then installed Windows Pro, using the ISO from the microsoft website, and pointed it to the Windows partition created in the partitioning scripts. It installed correctly, however, using REAgentC I noticed the installation was not using the recovery partition I made for it, but instead setup the recovery image in C:\Recovery\WindowsRE (C: being the mount point of the Windows partiton). So I tried making a Recovery\WindowsRE folder in the recovery partiton an copying the Winre.wim image there. This almost filled up the recovery partition.
When I used REAgentC to set the recovery image path, it said it completed successfuly, but, after enabling it, it silently moved back the Winre.wim file to C:\Recovery\WindowsRE and reset itself, emptying the recovery partition.
I then tried to enlarge the recovery partition to 1GB, and redo the move of the Winre.wim to the recovery partition, and this time REAgentC worked correctly, using the recovery partiton.

So, given this "adventure", I have two questions:
1) Is the installation process of Windows supposed to automatically detect and use the recovery partiton I provided, or am I supposed to do that manually, as I did?
2) What is the reccommended size of the recovery partition, given that 500MB (the size in the sample script) was not used automatically, and was silently "ignored" by REAgentC, and that 1GB worked correctly?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56201394-c4ed-706d-a904-187fc8d9abdf
* Version Independent ID: 120d1f68-7634-89f3-cac3-e96c2d2b3105
* Content: [UEFI/GPT-based hard drive partitions](https://docs.microsoft.com/en-gb/windows-hardware/manufacture/desktop/configure-uefigpt-based-hard-drive-partitions)
* Content Source: [manufacture/desktop/configure-uefigpt-based-hard-drive-partitions.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/configure-uefigpt-based-hard-drive-partitions.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
Hi @SamueleDecarli - If you're running Windows Setup, you don't have to manually partition your disk. The partition layout that we provide is usually used by people who are using DISM to apply an image. Windows Setup will take care of all of this for you.

**Comment by SamueleDecarli** [comment]
Hi, thanks, I understand that. I'm installing Windows alongside another OS, so I'm partitioning the whole disk manually. If I just point Windows to unallocated space, it will not create a recovery partition, if other partitions are present (eg a manually created, larger ESP). Hence why I'm trying to do so manually.

**Comment by kpacquer** [comment]
Hi @SamueleDecarli , to answer your questions:

1. Yes, Windows is supposed to automatically detect and use the recovery partiton you provided. However, the partition needs to be big enough for Windows RE, plus an additional amount of free space for WinRE to do its work. 

My guess is your partition is big enough for WinRE.wim, but didn't meet the free space requirement, based on the fact that the 1GB partition worked.

2. The recommended size depends on the size of WinRE.wim, and the free space requirement jumps up at 500MB. If your WinRE.wim is closer to 450MB, I'd recommend a partition size of 500MB. If it's closer to 500MB, I'd recommend a partition of 820MB or more.

_From https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/configure-uefigpt-based-hard-drive-partitions_ , **Recovery tools partition**
- If the partition is less than 500 MB, it must have at least 50 MB of free space.
- If the partition is 500 MB or larger, it must have at least 320 MB of free space.
