### ISSUE TITLE
Super helpful!

### ISSUE THREAD

**Issue by josuemunro** [MicrosoftDocs/commercialization-public#327]
Was stuck on the install screen and unable to do anything. This article sorted me out. Cheers!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abb6f8d1-f71e-3caf-a20e-cf37c1417dc5
* Version Independent ID: 298c1aae-fb6f-d81a-66a4-494383d3166c
* Content: [Windows Setup: Installing using the MBR or GPT partition style](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-installing-using-the-mbr-or-gpt-partition-style)
* Content Source: [manufacture/desktop/windows-setup-installing-using-the-mbr-or-gpt-partition-style.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/windows-setup-installing-using-the-mbr-or-gpt-partition-style.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
Hi @josuemunro - Thanks for the feedback!
