### ISSUE TITLE
Why is this not a complete list?

### ISSUE THREAD

**Issue by ciphernemo** [MicrosoftDocs/commercialization-public#328]
Where is Windows ADK 1511? The ADK 1607 and later is broken is creating deployments from a Windows 7 system.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78a7ade4-09ab-e0b2-4ace-a14b2d9c9bce
* Version Independent ID: 34de1342-2814-e81f-0f72-25395d07d6a6
* Content: [Download and install the Windows ADK](https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install#adkwin10)
* Content Source: [get-started/adk-install.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/get-started/adk-install.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by kpacquer** [comment]
Thanks Ciphernemo, I'll investigate the broken links for the 1511, 1607, 1703, and 1709 ADK versions.
For Win7, you can use the [Windows 7 WAIK](https://www.microsoft.com/en-us/download/details.aspx?id=5753).

**Comment by kpacquer** [comment]
Links fixed! However, the link for 1511 has been removed, as it's at the [end of support](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet).

**Comment by ciphernemo** [comment]
The 1511 is right here: [http://download.microsoft.com/download/3/8/B/38BBCA6A-ADC9-4245-BCD8-DAA136F63C8B/adk/adksetup.exe](http://download.microsoft.com/download/3/8/B/38BBCA6A-ADC9-4245-BCD8-DAA136F63C8B/adk/adksetup.exe)

Why not just include the link? People like me in IT still need to use it because Windows 7 is still officially supported, and I'm building my deployments for Windows 10 on a 7 machine. And it works fine. But Anything later than 1511 is NOT supported in Windows 7. So people like me still need 1511. And there's the official link from Microsoft's web site.
