### ISSUE TITLE
Outdated document

### ISSUE THREAD

**Issue by budu** [MicrosoftDocs/commercialization-public#331]
That document seems to be outdated, it did not work for a 6 years old computer. I had to use the Rufus utility to copy the ISO as a UEFI compatible boot drive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f937d36b-d39f-dfe5-8b82-2465918a3cc4
* Version Independent ID: 2941fc45-9c34-19b7-1c49-39cdc1b04ebf
* Content: [Install Windows from a USB Flash Drive](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/install-windows-from-a-usb-flash-drive)
* Content Source: [manufacture/desktop/install-windows-from-a-usb-flash-drive.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/install-windows-from-a-usb-flash-drive.md)
* Product: **windows-hardware**
* GitHub Login: @Joshua Baxter
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
Hi @budu - Thanks for the feedback. The note at the top of this page includes also includes a link to the Media Creation Tool, which makes it easy to create UEFI bootable media.
