### ISSUE TITLE
Does Touch Screen support BLE all feature same as USB device ? 

### ISSUE THREAD

**Issue by yuhua-cheng** [MicrosoftDocs/commercialization-public#346]
Contact Count Maximum Feature Report provided in USB device, the host will send a Get feature to request device response how many fingers supported. But, BLE device looks that host never request ?  

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 636df6ad-e544-55cc-728a-9d9d9c8ab9ff
* Version Independent ID: ccaabda8-6a6c-3235-0ba2-9dcee882c17b
* Content: [Required HID Top-Level Collections](https://docs.microsoft.com/zh-tw/windows-hardware/design/component-guidelines/touchscreen-required-hid-top-level-collections)
* Content Source: [design/component-guidelines/touchscreen-required-hid-top-level-collections.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/design/component-guidelines/touchscreen-required-hid-top-level-collections.md)
* Product: **windows-hardware**
* GitHub Login: @Joshua Baxter
* Microsoft Alias: **dongill**

**Comment by dawnwood** [comment]
Hi @yuhua-cheng Thank you for contacting the docs team. This sounds like a question or problem with the product, which you can report directly to the product team by typing "Feedback Hub" in the Start menu.
Best,
Dawn
