### ISSUE TITLE
Enable .NET Framework 3.5 by using the Add Roles and Features Wizard

### ISSUE THREAD

**Issue by WasJack** [MicrosoftDocs/commercialization-public#348]
I was installing an application and it required a reboot, and the .NET 3.5 installation failed. I downloaded .NET 3.5 and the installation failed again. I came here and followed the instructions for Add Roles and Features, and it worked. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de30ce3-a206-d305-6627-521758705bd2
* Version Independent ID: 4c87cc8a-4058-5c94-7a04-8c436dfc4054
* Content: [Enable .NET Framework 3.5 by using the Add Roles and Features Wizard](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/enable-net-framework-35-by-using-the-add-roles-and-features-wizard)
* Content Source: [manufacture/desktop/enable-net-framework-35-by-using-the-add-roles-and-features-wizard.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/enable-net-framework-35-by-using-the-add-roles-and-features-wizard.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
Thanks for the feedback!
