### ISSUE TITLE
This article for  BIOS based partition 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/commercialization-public#352]
This  article   can easily be  understand 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fba93cb-9f5e-ff02-bd54-737126c787ba
* Version Independent ID: 554ce88c-ef77-dc4c-5dc6-e8032bc79708
* Content: [Capture Images of Hard Disk Partitions Using DISM](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/capture-images-of-hard-disk-partitions-using-dism)
* Content Source: [manufacture/desktop/capture-images-of-hard-disk-partitions-using-dism.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/capture-images-of-hard-disk-partitions-using-dism.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
Thanks @RAJU2529 !
