### ISSUE TITLE
Troubleshooting of  RE should be  including here

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/commercialization-public#353]
last  week Bcd got corrupted, so Iand even i could not able  to  boot  repair your  computer , so i  deleted the recovery partition using windows 10 dvd .

But after logging in to windows, i recreated recovery partition on another disk, using  only  reagentc commands 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 189b3133-2a99-31d1-446d-9c0f44abd2df
* Version Independent ID: ff3bb437-1d58-23d6-08aa-752b500489fe
* Content: [Deploy Windows RE](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/deploy-windows-re)
* Content Source: [manufacture/desktop/deploy-windows-re.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/deploy-windows-re.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
Thanks for the suggestion. I'll take a look and see if it's a good place to add troubleshooting info.
