### ISSUE TITLE
Is it possible  to  convert MBR disk to  GPT disk without  losing data

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/commercialization-public#354]
Is it possible  to  convert the only C drive  into GPT partition, because  new  laptops comes  with 1TB  hdd , and user initially creates new  partition for OS  of size 250GB without converting GPT , but  disk is in MBR disk
and  the user  creates many partitions  with in 1TB hdd  , so when  if  he wants to convert GPT without  losing  data 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abb6f8d1-f71e-3caf-a20e-cf37c1417dc5
* Version Independent ID: 298c1aae-fb6f-d81a-66a4-494383d3166c
* Content: [Windows Setup: Installing using the MBR or GPT partition style](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-installing-using-the-mbr-or-gpt-partition-style)
* Content Source: [manufacture/desktop/windows-setup-installing-using-the-mbr-or-gpt-partition-style.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/windows-setup-installing-using-the-mbr-or-gpt-partition-style.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
Hi @RAJU2529 - Windows comes with the MBR2GPT utility that will convert your MBR disk to GPT. See the documentation here: https://docs.microsoft.com/en-us/windows/deployment/mbr-to-gpt

**Comment by RAJU2529** [comment]
thanks for your  reply sir,  but  little  confusion , if  C drive  is  already installed  windows 10 and  with some  partitions ,   booting windows PE 5.0, converting MBR to gpt means, will disk  0 is  wiped  or  not

**Comment by themar-msft** [comment]
The MBR2GPT tool is designed to not modify or delete data on the disk.
