### ISSUE TITLE
Compact  command 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/commercialization-public#355]
can i  use  same  command  to apply image  in desktop or  laptops with 1TB HDD   , choosing 250GB for  OS.

DISM /Apply-Image /ImageFile:E:\install.wim /Index:1 /ApplyDir:D:\ /compact

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9b960ec-90d5-e36c-f650-1296958b1e5a
* Version Independent ID: a69c63ba-60e8-23aa-b1bb-695cfb24c531
* Content: [Compact OS, single-instancing, and image optimization](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/compact-os)
* Content Source: [manufacture/desktop/compact-os.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/compact-os.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
Hi @RAJU2529 - To do this you'd have to create a 250GB partition on your 1TB hard drive, and apply the image to the 250GB drive.
