### ISSUE TITLE
when should use those commands

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/commercialization-public#356]
i am getting little confuse , when  should  we use those  commands 

1) after logged into windows 
2) booting windows PE disk
3)  booting  with recovery environment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc28f057-f2ce-9178-d5c7-fa1e1e2d0d33
* Version Independent ID: e2dc17f7-511a-834f-2461-7b55a6fb6a66
* Content: [BCD System Store Settings for UEFI](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/bcd-system-store-settings-for-uefi)
* Content Source: [manufacture/desktop/bcd-system-store-settings-for-uefi.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/bcd-system-store-settings-for-uefi.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by dawnwood** [comment]
Thank you for contacting us. Have you tried asking this question on our [product forum](https://social.msdn.microsoft.com/Forums/windowshardware/en-US/home), where engineers and mvps answer questions and listen to feedback?

**Comment by dawnwood** [comment]
Hi @RAJU2529 I'm closing this doc issue but encourage you to post on our product forum if you still have this question.
Best,
Dawn
