### ISSUE TITLE
export image commands 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/commercialization-public#358]
DISM.exe /Get-ImageInfo /ImageFile:C:\install.wim

DISM.exe /Export-Image /SourceImageFile:C:\Install.wim /SourceIndex:1 /DestinationImageFile:H:\Installnone.wim /DestinationName:Windows10 /Compress:none /CheckIntegrity

DISM.exe /Export-Image /SourceImageFile:C:\Install.wim /SourceIndex:1 /DestinationImageFile:H:\Installmax.wim /DestinationName:Windows10 /Compress:max /CheckIntegrity
DISM.exe /Export-Image /SourceImageFile:C:\Install.wim /SourceIndex:1 /DestinationImageFile:H:\Installfast.wim /DestinationName:Windows10 /Compress:fast /CheckIntegrity

DISM.exe /Export-Image /SourceImageFile:C:\Install.wim /SourceIndex:1 /DestinationImageFile:H:\Installrecovery.wim /DestinationName:Windows10 /Compress:recovery /CheckIntegrity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 945dac9d-8d33-9050-ea86-e566761a32e5
* Version Independent ID: f80f215d-8f33-6771-bb7a-5aebbc916cf1
* Content: [Capture and Apply Windows, System, and Recovery Partitions](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/capture-and-apply-windows-system-and-recovery-partitions)
* Content Source: [manufacture/desktop/capture-and-apply-windows-system-and-recovery-partitions.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/capture-and-apply-windows-system-and-recovery-partitions.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by dawnwood** [comment]
Hi @RAJU2529 Thank you for contacting us. Have you tried asking this question on our [product forum](https://social.msdn.microsoft.com/Forums/windowshardware/en-US/home), where engineers and mvps answer questions and listen to feedback?

**Comment by dawnwood** [comment]
Hi @RAJU2529 I'm closing this doc issue but encourage you to follow up on the product forum.
Best,
Dawn
