### ISSUE TITLE
Need more Speech Data!

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/commercialization-public#362]
There are 13 Speech data [here](https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/iot-core-feature-list#speech-data), is there plan to add more speech data? For example, Korean, Polish, Russian, etc.
Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0914e23d-b04a-d98f-c1d8-af957456fa4c
* Version Independent ID: 50a2686a-5bd1-d10f-41bb-d001186b1e95
* Content: [IoT Core feature list](https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/iot-core-feature-list)
* Content Source: [manufacture/iot/iot-core-feature-list.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/iot/iot-core-feature-list.md)
* Product: **windows-hardware**
* GitHub Login: @kpacquer
* Microsoft Alias: **themar**

**Comment by saraclay** [comment]
Yes, this document has now been updated.

**Comment by saraclay** [comment]
This update is now available.

**Comment by saraclay** [comment]
#please-close
