### ISSUE TITLE
Incorrect DISM /Capture-Image command line parameters

### ISSUE THREAD

**Issue by aleksigron** [MicrosoftDocs/commercialization-public#363]
Step 3 uses incorrect command line parameters for DISM /Capture-Image. The example uses parameters /ImageName and /ImageDescription, while according to the linked DISM command line options article, they should be /Name and /Description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99bdb06a-f4b0-7e9a-58ff-476c3216e98c
* Version Independent ID: 462fb2ef-da68-ff0d-9c8a-0d33f590fdce
* Content: [Deploy a Custom Image](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/deploy-a-custom-image)
* Content Source: [manufacture/desktop/deploy-a-custom-image.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/deploy-a-custom-image.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
hi @aleksigron - It should be /image and /description. I'll update the topic. Thanks for letting us know!

**Comment by RAJU2529** [comment]
The following commands are  worked 
dism.exe /Capture-Image /ImageFile:F:\win10ent.wim /CaptureDir:C:\ /Name:Enterprise

imagex /compress fast /flags "Professional" /check /scroll /capture C:\ F:\installcomfastflags.wim "Windows 10 Professional" /check /verify

imagex /compress maximum /flags "Professional" /check /scroll /capture C:\ F:\installpromax.wim "Windows 10 Professional" /check /verify

**Comment by RAJU2529** [comment]
i love to use the IMAGEX.exe  tool , it   gives  more flexibility because it will show, list of excluding folders , while capturing images, i have  included imagex.exe  inside winre.wim  and  in windows pe also .

**Comment by themar-msft** [comment]
The update has been merged and should be live later today. Thanks for the feedback!
