### ISSUE TITLE
Duplicated contents with activators. 

### ISSUE THREAD

**Issue by lawlxy** [MicrosoftDocs/commercialization-public#367]
This page is same as Activators: https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/activators

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3297876-a084-997b-4538-e998bb402608
* Version Independent ID: 954c6231-115a-8da1-6cb7-0b2cf8ad7de2
* Content: [Power policy configuration](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/power-policy-configuration)
* Content Source: [design/device-experiences/power-policy-configuration.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/design/device-experiences/power-policy-configuration.md)
* Product: **windows-hardware**
* GitHub Login: @Joshua Baxter
* Microsoft Alias: **dongill**

**Comment by dawnwood** [comment]
Hi @lawlxy You are right! I'll look into this and see what I can find out.

**Comment by dawnwood** [comment]
I removed the redundant topic and replaced it with a portal page that links to the child topics. Thanks again for noticing this!!
