### ISSUE TITLE
Separator for -Pids

### ISSUE THREAD

**Issue by randomascii** [MicrosoftDocs/commercialization-public#374]
It would be good to clarify what the separator for multiple PIDs passed to -Pids is. It's a space character, but it took me a while to realize that (I tried command and semicolon and then asked for help).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1633a3c5-6854-61fd-30e6-6be670c8f7e6
* Version Independent ID: 121f158d-9ad7-77a1-0858-4185b06522bc
* Content: [start](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/start)
* Content Source: [test/wpt/start.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/test/wpt/start.md)
* Product: **windows-hardware**
* GitHub Login: @Joshua Baxter
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks, @randomascii 

Aha! I **think** I see what you're talking about. You're saying we don't list this option:

        -Pids       pid [...]        Apply flags to processes pid [...].  Used in
                                     conjunction with Heap tracing.

Is that it? Plus, of course, the whole max 2 thing.

**Comment by randomascii** [comment]
It was not clear to me how multiple pids should be specified. These options come to mind:

-Pids 1234;6789
-Pids 1234,6789
-Pids 1234 6789

I now know that the last option is correct but I was unable to figure that out on my own - I had to ask.

I think the documentation should mention what separator should be used.

**Comment by EliotSeattle** [comment]
Thanks, @randomascii. I let this last part fall through the cracks. Appreciate your patience.
