### ISSUE TITLE
Incorret WimScript.ini Specifications

### ISSUE THREAD

**Issue by LEFT-ICE** [MicrosoftDocs/commercialization-public#379]
Content enclosed in double quotes such as `"\System Volume Information"` will be ignored. Double quotes should be removed.

Tested with DISM 10.0.17758.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c582f76-ac4c-1160-3451-6741f873ec63
* Version Independent ID: 5d127702-e356-7c6d-08d9-27cc5480a7e8
* Content: [DISM Configuration List and WimScript.ini Files](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism-configuration-list-and-wimscriptini-files-winnext#span-iddefaultexclusionlistspanspan-iddefaultexclusionlistspanspan-iddefaultexclusionlistspandefault-exclusion-list)
* Content Source: [manufacture/desktop/dism-configuration-list-and-wimscriptini-files-winnext.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/dism-configuration-list-and-wimscriptini-files-winnext.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
@LEFT-ICE -Thanks for letting us know! I'm updating the topic to remove the quotes.
