### ISSUE TITLE
Syntax Different for mounting WIM Files

### ISSUE THREAD

**Issue by kazysm** [MicrosoftDocs/commercialization-public#380]
See the cmdline HELP:
dism /mount-wim /?

Deployment Image Servicing and Management tool
Version: 10.0.14393.0

/Mount-Wim /WimFile:&lt;path_to_WIM_file&gt;
  {/Index:&lt;image_index&gt; | /Name:&lt;image_name&gt;}
  /MountDir:&lt;target_mount_directory&gt; [/readonly]

  Mounts the WIM file to the specified directory so that it is available for
  servicing.
  Use /ReadOnly to set the mounted image to have read-only permissions.

    Examples:
      DISM.exe /Mount-Wim /WimFile:C:\test\images\myimage.wim /index:1
        /MountDir:C:\test\offline

      DISM.exe /Mount-Wim /WimFile:C:\test\images\myimage.wim /index:1
        /MountDir:C:\test\offline /ReadOnly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8062f53-f72a-ee5e-25aa-df0009d38cfa
* Version Independent ID: c00e24aa-fce9-4731-f407-f44f8c19ae6e
* Content: [Modify a Windows Image Using DISM](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/mount-and-modify-a-windows-image-using-dism)
* Content Source: [manufacture/desktop/mount-and-modify-a-windows-image-using-dism.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/mount-and-modify-a-windows-image-using-dism.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
Hi @kazysm - You can use /mount-image to mount all the different image types, including WIMs.
