### ISSUE TITLE
Featuremerger

### ISSUE THREAD

**Issue by pre10nder** [MicrosoftDocs/commercialization-public#382]
I get this error always when running buildfm oem and in buildimage, I have working for four days and cannot get it to work 
 Processing rpi2FMFileList.xml
  Error: Featuremerger failed for rpi2FMFileList.xml. See C:\iot-adk-addonkit-master\Build\arm\buildfm_bsp_rpi2.log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce148d79-ed3c-c6e5-c643-2638854bd34f
* Version Independent ID: 0de2b8fa-69a6-0446-a354-091548a17c7c
* Content: [Lab 1b: Add an app to your image](https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/deploy-your-app-with-a-standard-board)
* Content Source: [manufacture/iot/deploy-your-app-with-a-standard-board.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/iot/deploy-your-app-with-a-standard-board.md)
* Product: **windows-hardware**
* GitHub Login: @kpacquer
* Microsoft Alias: **themar**

**Comment by saraclay** [comment]
Hi @pre10nder, do you mind reposting this in our MSDN forums? We have staff dedicated to monitoring these forums and could better assist you there. Thanks!

MSDN forums: https://social.msdn.microsoft.com/forums/en-US/home?forum=WindowsIoT
