### ISSUE TITLE
Buildimage error

### ISSUE THREAD

**Issue by pre10nder** [MicrosoftDocs/commercialization-public#384]
buildimage ProductA test error any solution?
ThreadId7764 ERROR: [00:11:36] onecore\base\cbs\mobile\updatedll\lib\executeupdate.cpp, UpdateMain::ExecuteUpdate, line 538, Error  , ExecuteUpdate was called before completion of PrepareUpdate
ThreadId7764 ERROR: [00:11:36] onecore\base\cbs\mobile\updatedll\lib\executeupdate.cpp, UpdateMain::ExecuteUpdate, line 864, Error  , hr = 0x80070016
ThreadId7764 ERROR: Imaging!UpdateImage: Failed call to UpdateDLL::ExecuteUpdate with error code: -2147024874 (0x80070016)
Error : Build failed. See Log for details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f7b1fcf-a299-2f26-e2bb-9acc4f7fa6b4
* Version Independent ID: b0a6652d-54eb-7416-059d-a1c86fda93ac
* Content: [Lab 1a: Create a basic image](https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/create-a-basic-image)
* Content Source: [manufacture/iot/create-a-basic-image.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/iot/create-a-basic-image.md)
* Product: **windows-hardware**
* GitHub Login: @kpacquer
* Microsoft Alias: **themar**

**Comment by saraclay** [comment]
Hi @pre10nder, do you mind reposting this in our MSDN forums? We have staff dedicated to monitoring these forums and could better assist you there. Thanks!

MSDN forums: https://social.msdn.microsoft.com/forums/en-US/home?forum=WindowsIoT
