### ISSUE TITLE
which command is more usefull

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/commercialization-public#387]
1) 
Dism /Capture-Image /ImageFile:F:\install.wim /CaptureDir:C:\  /Name:Windows10 /Description:Professional /ConfigFile:F:\Config.ini /Compress:fast /CheckIntegrity /Verify /NoRpFix /EA
or
2)
Dism /Capture-Image /ImageFile:F:\install.wim /CaptureDir:C:\  /Name:Windows10 /Description:Professional /Compress:fast /CheckIntegrity /Verify /NoRpFix /EA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99bdb06a-f4b0-7e9a-58ff-476c3216e98c
* Version Independent ID: 462fb2ef-da68-ff0d-9c8a-0d33f590fdce
* Content: [Deploy a Custom Image](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/deploy-a-custom-image)
* Content Source: [manufacture/desktop/deploy-a-custom-image.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/deploy-a-custom-image.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
Hi @RAJU2529 - If you want to use a config.ini, #1 is more useful. If you don't need to, then #2 is fine. You also likely don't need to use the /ea option for either.
