### ISSUE TITLE
Whats the difference between  "Capture-CustomImage"  and  "Capture-Image"

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/commercialization-public#388]
when should  we  use  the  following command  while capturing image and  why  , what are the  benefits 

DISM.exe /Capture-CustomImage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99bdb06a-f4b0-7e9a-58ff-476c3216e98c
* Version Independent ID: 462fb2ef-da68-ff0d-9c8a-0d33f590fdce
* Content: [Deploy a Custom Image](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/deploy-a-custom-image)
* Content Source: [manufacture/desktop/deploy-a-custom-image.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/deploy-a-custom-image.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
@RAJU2529 - The description in that topic says that /Capture-CustomImage is for WIMBoot images, which don't apply to Windows 10.
