### ISSUE TITLE
added device drivers

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/commercialization-public#389]
i  mounted the  install.wim  with /optimize  command  and  then   i  added  boot critical drivers and  signed drivers with /forceunsigned  command  
and  then  i  cleaned up image with /StartComponentCleanup /Reset base /ScratchDir:C:\Temp
atlast  i unmounted the image , then i exported new image with /checkintegrity 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6882a3cf-a216-92c0-24b0-0cb3add524f5
* Version Independent ID: 15450cea-d7e0-0465-824b-e927528a947c
* Content: [Add Device Drivers to Windows During Windows Setup](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/add-device-drivers-to-windows-during-windows-setup)
* Content Source: [manufacture/desktop/add-device-drivers-to-windows-during-windows-setup.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/add-device-drivers-to-windows-during-windows-setup.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
Thanks for the comment - Did the exported image include the drivers you injected?

**Comment by RAJU2529** [comment]
>           Thanks for the comment - Did the exported image include the drivers you injected?
yes  sir  ,   with  that  image  i  installed in my laptop, running smoothing
