### ISSUE TITLE
got  confused 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/commercialization-public#390]
/Capture-CustomImage only captures the customization files. It can’t be used to capture installation files into a new WIM.
Keep the install.wim and custom.wim files together. Don't switch out either the custom.wim file or the install.wim file.
You can only capture the custom image once. Don’t remove or recapture a custom.wim after capturing the incremental file changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44897cb8-47b7-ed7a-9ccd-3d8d92df5213
* Version Independent ID: 2c52cf81-2fd5-672e-12a3-b1a4d7958a06
* Content: [DISM Image Management Command-Line Options](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism-image-management-command-line-options-s14#capture-customimage)
* Content Source: [manufacture/desktop/dism-image-management-command-line-options-s14.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/dism-image-management-command-line-options-s14.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
Hi @RAJU2529 - I believe Capture-CustomImage is only for WimBoot images, which don't apply to Windows 10.

**Comment by RAJU2529** [comment]
what is  wimboot image ,  you mean for boot.wim  or winre,wim

**Comment by themar-msft** [comment]
WIMBoot was for Windows 8.1 and is similar to Compact OS in Windows 10, https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/compact-os
