### ISSUE TITLE
is make any difference by compact.exe

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/commercialization-public#391]
i am running windows 10 enterprise on SSD  on 209GB , if i  run below  command to  change from non-compacted to compacted OS:
Compact.exe /CompactOS:always
after  running this  command ,  is windows 10 make any difference, do i get all future updates for all the products including  office 2016 and windows 10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9b960ec-90d5-e36c-f650-1296958b1e5a
* Version Independent ID: a69c63ba-60e8-23aa-b1bb-695cfb24c531
* Content: [Compact OS, single-instancing, and image optimization](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/compact-os)
* Content Source: [manufacture/desktop/compact-os.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/compact-os.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by kpacquer** [comment]
Yes, you can use Compact.exe to save space on your existing installations. You'll continue to get future updates for Windows 10 and other installed products like Office 2016.
Saw a nice write-up here showing how to do this, plus other tricks to save drive space: https://www.windowscentral.com/how-reduce-windows-10-footprint-your-pc .
