### ISSUE TITLE
dism error 80  received

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/commercialization-public#393]
today i tried to capture the image  using Windows 10 PE 5.0  ( created by me ) from C windows partition to the free space partition F drive 

F is free partition to save captured images 144Gb free
C is windows installed partition 94GB used

I tried two different commands, 1st one is  got success and 2nd got failed, received  error 80  : the file exists 

the first  command is success
Dism /Capture-Image /ImageFile:F:\install.wim /CaptureDir:C:\ /Name:Windows10 /Description:Professional

the second command  is  failed
Dism /Capture-Image /ImageFile:F:\install.wim /CaptureDir:C:\ /Name:Windows10 /Description:Professional /CheckIntegrity /Verify  /EA

uploaded dism.log file
https://1drv.ms/u/s!AmZoRRusRV59lExxthHO8Ea5RW3c

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44897cb8-47b7-ed7a-9ccd-3d8d92df5213
* Version Independent ID: 2c52cf81-2fd5-672e-12a3-b1a4d7958a06
* Content: [DISM Image Management Command-Line Options](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism-image-management-command-line-options-s14)
* Content Source: [manufacture/desktop/dism-image-management-command-line-options-s14.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/dism-image-management-command-line-options-s14.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**
![p_20180929_134834](https://user-images.githubusercontent.com/3296790/46248978-ef809d00-c43e-11e8-978b-cf1b8cf0bcee.jpg)

**Comment by dawnwood** [comment]
Hi @RAJU2529 Thank you for contacting us. Have you tried asking this question on our [product forum](https://social.msdn.microsoft.com/Forums/windowshardware/), where engineers and mvps answer questions and listen to feedback?

**Comment by dawnwood** [comment]
Hi @RAJU2529 I'm closing this doc issue, but I encourage to you to follow up either on the product forum mentioned above, or by clicking the "Product Feedback" link at the bottom of topics on docs.microsoft.com.
Best,
Dawn
