### ISSUE TITLE
which set of  commands is correct 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/commercialization-public#394]
set 1
DISM.exe /capture-ffu /imagefile=F:\flash.ffu /capturedrive=\\.\PhysicalDrive0 /name:disk0 /description:"Windows 10 FFU"
DISM.exe /Apply-ffu /imagefile=F:\flash.ffu /ApplyDrive:\\.\PhysicalDrive0 /name:disk0 

set 2
DISM.exe /Capture-Ffu /ImageFile:F:\flash.ffu /CaptureDrive:\\.\PhysicalDrive0 /Name:Drive0 /name:disk0 /description:"Windows 10 FFU"
DISM.exe /Apply-Ffu /ImageFile:F:\flash.ffu /ApplyDrive:\\.\PhysicalDrive0 /name:disk0 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c50e4a13-0054-5b8e-9ac1-8895c4642e27
* Version Independent ID: 0f6e0c6a-211b-7f64-3f54-63a413a250eb
* Content: [Windows Full Flash Update (FFU) images](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/deploy-windows-using-full-flash-update--ffu)
* Content Source: [manufacture/desktop/deploy-windows-using-full-flash-update--ffu.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/deploy-windows-using-full-flash-update--ffu.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by themar-msft** [comment]
Hi @RAJU2529 - Both semicolons and equal signs can be used in this command, so both should work. The second command specifies "name" twice though, so that may not work.
