### ISSUE TITLE
Why are we still stuck in the 20th century?

### ISSUE THREAD

**Issue by danofsatx** [MicrosoftDocs/commercialization-public#395]
This is 2018 - WINS has been dead since Y2K. When can we finally loose the 15 character hostname limitation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbfbb7a5-4f30-6ce8-6297-f4d464d84d38
* Version Independent ID: d29b3d67-c73e-bece-5cad-df84da05eb81
* Content: [ComputerName](https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-shell-setup-computername)
* Content Source: [customize/desktop/unattend/microsoft-windows-shell-setup-computername.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/customize/desktop/unattend/microsoft-windows-shell-setup-computername.md)
* Product: **windows-hardware**
* GitHub Login: @alhopper-msft
* Microsoft Alias: **alhopper**

**Comment by dawnwood** [comment]
Hi @danofsatx good question! Unfortunately it's not a question that the documentation can answer. If you want to find out more, please feel free to pose this question to the [hardware forum](https://social.msdn.microsoft.com/Forums/windowshardware/), where engineers and mvps answer product queries and listen to customer feedback.

**Comment by dawnwood** [comment]
Hi @danofsatx I'm closing this issue now, good luck finding an answer in the forum!
