### ISSUE TITLE
No way to disable wake-up events for modern standby under Windows 10

### ISSUE THREAD

**Issue by makedir** [MicrosoftDocs/commercialization-public#396]
Why is there still no way to disable any wake-up events for HID devices connected via Bluetooth or even USB for modern standby... !? With good old S3, you were able to disable all wake-up events via powercfg. This is not possible anymore for modern standby, and a terrible design. Most users dont want a wake up for example via a Bluetooth mouse, after the device enters sleep. This has to be implemented in Windows 10. How can a basic important feature like this still be missing 3 years after Windows 10 went stable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bd622de-b307-16bb-49dd-0ae2fd4f2496
* Version Independent ID: 8b976b76-a62a-aa1e-751f-0b240f33cd26
* Content: [Bluetooth power management for modern standby platforms](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/bluetooth-power-management-for-modern-standby-platforms)
* Content Source: [design/device-experiences/bluetooth-power-management-for-modern-standby-platforms.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/design/device-experiences/bluetooth-power-management-for-modern-standby-platforms.md)
* Product: **windows-hardware**
* GitHub Login: @Joshua Baxter
* Microsoft Alias: **dongill**

**Comment by EliotSeattle** [comment]
Hi @makedir.
Thanks for the feedback. I really don't know the answer to the question, but the people who do pay attention to input in Feedback Hub. In Windows 10, click the Windows key, type Feedback Hub in the search box, and open Feedback Hub. Add as many details as you can.  The developer and PM teams really do read the feedback.
Also, I'll find a contact on Modern Standby that I can pass this on to. In the meantime, if you have any questions or issues about the documentation, let me know.
