### ISSUE TITLE
Metadata Presented on Microsoft Docs

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/commercialization-public#399]
The following content is at the top of this document, I believe it's supposed to be part of the document metadata and not sent to the browser.
---
title: Unified Write Filter (UWF) feature description: Unified Write Filter (UWF) feature MSHAttr:

'PreferredSiteName:MSDN'
'PreferredLib:/library/windows/hardware' ms.assetid: 05f82dbf-64e7-4ed2-8932-9abcfad59598 author:themar-msft ms.author:themar ms.date: 05/02/2017 ms.topic: article ms.prod: windows-hardware
ms.technology: windows-oem
---

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087bf55f-0969-7441-ef89-ed7ab562cde7
* Version Independent ID: 8fbe0a94-2af7-4e42-3d24-bfbcf9aff2a5
* Content: [ms.technology: windows-oem](https://docs.microsoft.com/en-us/windows-hardware/customize/enterprise/unified-write-filter)
* Content Source: [customize/enterprise/unified-write-filter.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/customize/enterprise/unified-write-filter.md)
* GitHub Login: @Joshua Baxter

**Comment by EliotSeattle** [comment]
Thanks, @ChrisKibble!
@kpacquer, can you please format this errant metadata and put it back in its cage?

**Comment by kpacquer** [comment]
Metadata wrangled and contained! Thanks Chris for letting us know.
