### ISSUE TITLE
Modern Standby Test

### ISSUE THREAD

**Issue by Paul-review** [MicrosoftDocs/commercialization-public#437]
Will Modern Standby also work if I have a discrete graphics card solution ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 826304fe-21e9-1e3a-9e52-a8f90d0fb078
* Version Independent ID: 2679cec3-e653-96a3-3d91-a643a917fcce
* Content: [Modern Standby Basic Requirement Test on AC-power Source](https://docs.microsoft.com/en-us/windows-hardware/test/hlk/testref/c0c51f07-5b17-4b26-a7ce-bfc9e7611dac#parameters)
* Content Source: [test/hlk/testref/c0c51f07-5b17-4b26-a7ce-bfc9e7611dac.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/test/hlk/testref/c0c51f07-5b17-4b26-a7ce-bfc9e7611dac.md)
* Product: **windows-hardware**
* GitHub Login: @sapaetsc-msft
* Microsoft Alias: **sapaetsc**

**Comment by dawnwood** [comment]
You can use a discrete graphics card under as long as the dGPU is implemented with VRAM that can be put into self-refresh when the dGPU is in D3. The graphics driver must be able to perform this self-refresh operation.
