### ISSUE TITLE
Incorrect MTU size definition

### ISSUE THREAD

**Issue by I-gor-C** [MicrosoftDocs/commercialization-public#45]
The definition of MTU size in https://docs.microsoft.com/en-us/windows-hardware/design/compatibility/device-network-lan#device.network.lan.largesendoffload (Device.Network.LAN.MTUSize) doesn't match the definition of *JumboPacket registry key in https://docs.microsoft.com/en-us/windows-hardware/drivers/network/keywords-that-can-be-edited . Additionally, the MTU size definition is located in the LSO subsection which seems incorrect. Please see the full discussion in https://github.com/MicrosoftDocs/windows-driver-docs/issues/254

**Comment by sapaetsc-msft** [comment]
Thanks for your feedback! We've fixed the formatting error that made it appear that the MTU size definition was under LSO. It now appears as its own entry, as it should. Meanwhile, we're working on clarifying the MTU size definition and hope to provide the improved wording in the next release.
