### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by ferenczy** [MicrosoftDocs/commercialization-public#452]
I had WPT installed for long time and I have been successfully using it but when I needed it today, I noticed it's gone for some reason. I definitely didn't (intentionally) uninstall it. Start menu items were still there but their targets were missing. There was no subdirectory `Windows Performance Toolkit` inside the directory `c:\Program Files (x86)\Windows Kits\8.1\` anymore. I have no clue what happened.

So I was looking how to install it back. I found this article, so I have [downloaded](https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install) _AIK for Windows 7_ (probably previous name for the ADK), becasue I'm using Windows 7, and run the installer just to find out there's no option to install WPT. I have even tried to download _ADK for Windows 10_ but it's same, there's no option to install WPT.

Options available in ADK for Windows 10:

- App Compatibility Tools
- Deployment Tools
- Windows PE
- Imaging and Configuration Designer
- Configuration Designer
- User State Migration Tool
- Volume Activation Management Tool
- Media eXperience Analyzer

In the end, I simply [downloaded Windows 8.1 SDK](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive) and installed WPT form there. It was fast and simple.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42deffc9-20b4-5d69-cbac-a76e7cf23bda
* Version Independent ID: 0ae586a5-cf44-a40c-845d-1c04d0be8d64
* Content: [Windows Performance Toolkit](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/)
* Content Source: [test/wpt/index.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/test/wpt/index.md)
* Product: **windows-hardware**
* GitHub Login: @Joshua Baxter
* Microsoft Alias: **eliotgra**

**Comment by dawnwood** [comment]
Hi @ferenczy I'm sorry that this happened. Glad you found a solution that works for you. Here's another resource you might try if that happens again, or if you want to update to a more recent version: [Download and Install the Windows ADK](https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install).
