### ISSUE TITLE
Additional content on Support Blog for file association with DISM

### ISSUE THREAD

**Issue by AamirAllaq** [MicrosoftDocs/commercialization-public#461]
Hi.
It appears there's additional content available for this topic on a Microsoft blog post written by a support engineer. 
https://blogs.technet.microsoft.com/windowsinternals/2017/10/25/windows-10-how-to-configure-file-associations-for-it-pros/. 
It would be great to incorporate that content within official docs here, so it can be officially and reliably referenced.
Thanks.

**Comment by kpacquer** [comment]
Thanks Aamir! Great idea. We're updating our recommendations based on the blog post. The new recommendations should be live in a day or two.
