### ISSUE TITLE
Requirement to not have an S3 object is wrong

### ISSUE THREAD

**Issue by superm1** [MicrosoftDocs/commercialization-public#465]
This comment is with regard to this page:
https://github.com/MicrosoftDocs/commercialization-public/blob/master/design/device-experiences/platform-design-for-modern-standby.md

Under "Other Platform requirements"
There is this bullet point:

> The system ACPI firmware must not provide an S3 object in the root of the namespace. Windows supports a platform exposing either the S3 object or the ACPI_S0_LOW_POWER_IDLE FADT flag, but not both at the same time. Note  The FADT bit takes precedence over an S3 object.

This is in complete contrast to many other pages that reference that an S3 object can still be present in the ACPI tables. I believe this bullet should be modified to completely remove the first sentence.  The rest of it is accurate.

**Comment by dawnwood** [comment]
Thank you for finding and reporting this. You are correct. I am changing this now and will close this issue once the update is live.

**Comment by dawnwood** [comment]
This is fixed. Thanks again for raising the issue and making the docs more accurate.
