### ISSUE TITLE
Include update policy configuration to receive device update center published updates

### ISSUE THREAD

**Issue by scout208** [MicrosoftDocs/commercialization-public#478]
In the [Device Update Center User Guide - Step 6](https://docs.microsoft.com/en-us/windows-hardware/service/iot/using-device-update-center#step-6-validate-the-updates-on-device), it lists how to validate the updates available on Windows update on the device. It says "the device will detect the published update, download and install automatically (based on the update policies configured)."

It would be helpful to know what update policies need to be configured to let the device download the update. I'm trying to validate my update on my device but it won't update and I don't know if my policies are configured correctly or not.

**Comment by saraclay** [comment]
#in-progress

**Comment by saraclay** [comment]
I think this is being taken care of in the forums. #please-close
