### ISSUE TITLE
PCIe NVMe SSD support

### ISSUE THREAD

**Issue by JarvisZJ** [MicrosoftDocs/commercialization-public#492]
How about PCIe NVME disk support for System cert?  The Disk stress 'Hard Disk Drive Testing Prerequisites' did not list any NVMe description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1e56a0b-a2b7-4258-3b29-3c98f3f022b6
* Version Independent ID: 267afb31-43f8-5cab-13e8-950b78c55bb7
* Content: [Disk Stress (LOGO)](https://docs.microsoft.com/en-us/windows-hardware/test/hlk/testref/738735f7-245a-4b39-9d81-20339ce31fd4)
* Content Source: [test/hlk/testref/738735f7-245a-4b39-9d81-20339ce31fd4.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/test/hlk/testref/738735f7-245a-4b39-9d81-20339ce31fd4.md)
* Product: **windows-hardware**
* GitHub Login: @dawn.wood
* Microsoft Alias: **dawnwood**

**Comment by dawnwood** [comment]
Hi @JarvisZJ I'm not sure about the answer to this but I'll see what I can find out.

**Comment by JarvisZJ** [comment]
Ok, Did you have any update? Or which we cat get the NVMe support information for Disk Stress test?

**Comment by dawnwood** [comment]
I have emailed the subject matter experts and hope to have an answer for you soon. I apologize for the delay.

**Comment by dawnwood** [comment]
The Disk Stress (LOGO) works for any device, including NVMe devices, but you can also use the separate [LOGO IO test for NVMe devices](https://docs.microsoft.com/en-us/windows-hardware/test/hlk/testref/90f535f2-9cfe-49ee-9e4a-852ae6770b9a). 
This test specifically covers the needs of NVMe device, which includes SQ/CQ/Queue size variations and IO distributions. All the NVMe tests are covered by the Device.Storage.ControllerDrive.NVMe.BasicFunction specification.

**Comment by JarvisZJ** [comment]
OK, It is even better to update NVMe Disk to the 'Hard Disk Drive Testing Prerequisites' section. Thank you very much.

**Comment by dawnwood** [comment]
Thank you for the feedback. I will see if we can update the https://docs.microsoft.com/en-us/windows-hardware/test/hlk/testref/hard-disk-drive-testing-prerequisites topic to include this information. 
Best,
Dawn
