### ISSUE TITLE
The NTP server is slow and Can't change server on image from Guide.

### ISSUE THREAD

**Issue by awong1900** [MicrosoftDocs/commercialization-public#5]
https://docs.microsoft.com/zh-cn/windows-hardware/manufacture/iot/update-the-time-server
Can we change the default image with multi ntp server?

And I try to create a package definition file with the Guide, But it is still not work.

**Comment by joshbax-msft** [comment]
Hey there--sorry for missing this. I'll reach out to the team and see if I can get an answer for you.

**Comment by parameshbabu** [comment]
@awong1900 , can you let us know the error you are getting? Are you using the FFU from Microsoft or creating one on your own? 
Let us know the detailed steps you followed to help you further .
Thanks,

**Comment by awong1900** [comment]
@parameshbabu I follow the link to make own FFU which change the NTP. I can see the registry is changed. But when i use command to check, "w32tm /query /peers", it is still default.

**Comment by parameshbabu** [comment]
@awong1900 The issue is in the reg key specified. <RegKey KeyName="$(hklm.system)\CurrentControlSet\Services\w32time\Parameters">. The document states hklm.software that is incorrect. I'll update the document shortly.

**Comment by awong1900** [comment]
Thank you.

**Comment by joshbax-msft** [comment]
Doc update has been published, and repo now reflects the change. Let us know if you're still having any trouble.
