### ISSUE TITLE
Adding registry setting doesn't work as expected

### ISSUE THREAD

**Issue by JeffMushmo** [MicrosoftDocs/commercialization-public#501]
Following these instructions: [Build a package for your test files](https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/add-a-registry-setting-to-an-image#build-a-package-for-your-test-files)

The issue is with the Registry.Settings.wm file that gets generated. Here are the contents:
```
<?xml version="1.0" encoding="utf-8"?>
<identity xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Settings" namespace="Registry" owner="$(OEMNAME)" legacyName="$(OEMNAME).Registry.Settings" xmlns="urn:Microsoft.CompPlat/ManifestSchema.v1.00">
    <onecorePackageInfo targetPartition="MainOS" releaseType="Production" ownerType="OEM" />
    <regKeys>
        <regKey keyName="$(hklm.system)\CurrentControlSet\Services\wuauserv" />
        <regKey keyName="Start" />
        <regKey keyName="REG_SZ" />
        <regKey keyName="0x4" />
    </regKeys>
</identity>
```

Obviously the 3 latter regKey elements should actually be within the regValue element with their respective attributes.

After changing the Registry.Settings content to, then rebuilding:
```
<?xml version="1.0" encoding="utf-8"?>
<identity xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Settings" namespace="Registry" owner="$(OEMNAME)" legacyName="$(OEMNAME).Registry.Settings" xmlns="urn:Microsoft.CompPlat/ManifestSchema.v1.00">
    <onecorePackageInfo targetPartition="MainOS" releaseType="Production" ownerType="OEM" />
    <regKeys>
        <regKey keyName="$(hklm.system)\CurrentControlSet\Services\wuauserv">
            <regValue
 name="Start" type="REG_SZ"
 value="0x4" />
        </regKey>
    </regKeys>
</identity>

```
I get the following error:
This will take a while...
ThreadId14216 ERROR: [00:11:54] onecore\base\cbs\mobile\iucore\iupartition.cpp, IUPartition::ProcessIndividualCbsPackages, line 911, Error  , Failed to finalize client, error is 0x80188309
ThreadId14216 ERROR: [00:11:55] onecore\base\cbs\mobile\iucore\iupartition.cpp, IUPartition::ProcessAllCbsPackages, line 1245, Error  , Failed to process individual packages while Commit, error is 0x80188309
ThreadId14216 ERROR: [00:11:55] onecore\base\cbs\mobile\updatedll\lib\executeupdate.cpp, UpdateMain::Commit, line 1422, Error  , Failed to commit partition MainOS, error is 0x80188309
ThreadId14216 ERROR: [00:11:55] onecore\base\cbs\mobile\updatedll\lib\executeupdate.cpp, UpdateMain::ExecuteUpdate, line 1131, Error  , Commit failed, error is 0x80188309
ThreadId14216 ERROR: [00:12:11] onecore\base\cbs\mobile\updatedll\lib\executeupdate.cpp, UpdateMain::ExecuteUpdate, line 1243, Error  , hr = 0x80188309
ThreadId14216 ERROR: Imaging!UpdateImage: Failed call to UpdateDLL::ExecuteUpdate with error code: -2145877239 (0x80188309)
Error: Build failed
False

**Comment by JeffMushmo** [comment]
Just did
[https://social.msdn.microsoft.com/Forums/en-US/7127a56f-c0f6-47c8-8f03-53e968462e28/adding-registry-setting-doesnt-work-as-expected?forum=WindowsIoT](https://social.msdn.microsoft.com/Forums/en-US/7127a56f-c0f6-47c8-8f03-53e968462e28/adding-registry-setting-doesnt-work-as-expected?forum=WindowsIoT)

**Comment by saraclay** [comment]
Great - hopefully this will help you quicker. Best of luck!

**Comment by saraclay** [comment]
#please-close
