### ISSUE TITLE
CPU analysis document seems to swap conventional use of "top" and "bottom" of stack

### ISSUE THREAD

**Issue by johndog** [MicrosoftDocs/commercialization-public#502]
The CPU sample table lists these entries:

Column | Description
--- | ---
Function | The function at the bottom of the stack.
Module | The module that contains the function at the bottom of the stack.

This seems unlikely to be accurate; the function at the bottom of the stack is invariably a thread entry point, which is not very interesting for profiling purposes.  

I think this document (not just the table) takes the confusing position that the stack starts at the top and grows downward.  That is literally an upside-down stack:  stacks grow upward, and therefore the top is by definition the most volatile entry.  The thread stack is even faithful to the physical metaphor as it occupies memory, since the topmost item of the stack always occupies the earliest address, and the stack pointer moves backward to accommodate new function calls.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed3e9e0d-0583-6819-8ff4-0ee6cdb9c983
* Version Independent ID: 0386dfa3-0fc4-0de7-00f2-702f921eca3e
* Content: [CPU Analysis](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/cpu-analysis)
* Content Source: [test/wpt/cpu-analysis.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/test/wpt/cpu-analysis.md)
* Product: **windows-hardware**
* GitHub Login: @Joshua Baxter
* Microsoft Alias: **eliotgra**

**Comment by dawnwood** [comment]
Hi @johndog I'm looking into this now. I also see your pull request, I'll address both once I do a bit of digging on my end.
Best,
Dawn
