### ISSUE TITLE
add quotes to differentiate fieldName and value.

### ISSUE THREAD

**Issue by studiowebux** [MicrosoftDocs/commercialization-public#514]
In Job Explorer, press CTRL+Q to open the query pane, and search for jobs where Name Equals Windows Logo Kit- Prepare client for submission. === In Job Explorer, press CTRL+Q to open the query pane, and search for jobs where "Name" Equals "Windows Logo Kit- Prepare client for submission". to know which field to write in the value and field name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28c99f4e-9f30-7ff2-0f41-30971414643e
* Version Independent ID: 9bfbb161-5785-67c3-436e-04ba6942a797
* Content: [LoadGen SC LMS Workaround](https://docs.microsoft.com/en-us/windows-hardware/test/hlk/testref/loadgen-sc-lms-workaround)
* Content Source: [test/hlk/testref/loadgen-sc-lms-workaround.md](https://github.com/MicrosoftDocs/commercialization-public/blob/staging/test/hlk/testref/loadgen-sc-lms-workaround.md)
* Product: **windows-hardware**
* GitHub Login: @dawnwood
* Microsoft Alias: **dawnwood**

**Comment by EliotSeattle** [comment]
Thanks, @studiowebux. I've made some edits to make the steps clearer. Should be live within a day.
