### ISSUE TITLE
DISM (ADK) Host OS Windows 7 no longer supported

### ISSUE THREAD

**Issue by computeronix** [MicrosoftDocs/commercialization-public#54]
Can you work with the Product Group to review this page https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism-supported-platforms as with the latest version of Windows 10 ADK 1703 / 1709 it will no longer install on a Windows 7 SP1 OS as it gives an unsupported platform error.

**Comment by themar-msft** [comment]
I'll look into whether ADK can install on earlier versions of Windows, but since the ADK isn't the only way to get newer version of DISM onto a PC, the table still applies.
