### ISSUE TITLE
SkipRearm confusion in sysprep--generalize--a-windows-installation

### ISSUE THREAD

**Issue by loosus456** [MicrosoftDocs/commercialization-public#61]
The following paragraph exists:

> In previous versions of Windows, you could use the SkipRearm answer file setting to reset the Windows Product Activation clock when running sysprep. If you are using a volume licensing key or a retail product key, you don't have to use SkipRearm because Windows is automatically activated.

The paragraph states that you could use SkipRearm in previous versions of Windows.  So, is this statement insinuating that you can no longer use SkipRearm in recent versions of Windows?  If it's not insinuating this, then why mention previous versions of Windows at all?  Why not just just say "You can use the SkipRearm answer file setting to reset the..."?

If you cannot use SkipRearm in new versions of Windows, then (a) this fact needs to be clearly stated and (b) it needs to indicate in which version of Windows this change was made so that IT professionals know whether they can use it for their particular environments, as not every IT professional is using the most recent versions of Windows.

**Comment by themar-msft** [comment]
Hi Jason,

Thanks for pointing this out. For most Windows 10 deployment scenarios, `skiprearm` is no longer needed. I can add some clarification to the topic.
