### ISSUE TITLE
"discrete pad" definition

### ISSUE THREAD

**Issue by chsiuchen** [MicrosoftDocs/commercialization-public#87]
As title, we are confused about HLK: "Device Type" definition. For precision touchpad with external button, we need to report this device as "discrete pad" in the past. In addition, Elan follows the direction in Device Capabilities Feature Report and the Sample Report Descriptor in the Precision Touchpad Implementation Guide to report the Precision touchpad with external buttons as "discrete pad".

Recently, we noticed the criteria for the PTP HLK test item “Device Type” had been changed for a non-clickable touchpad. The device type should be showed as “No Pad(Device?) Type” instead of “Discrete Pad”. To meet the new criteria, we should not define the Pad type (Page 0x0D, Usage 0x59) in device capabilities feature report. If we don’t define the pad type, will it violate the specification in the Precision Touchpad Implementation Guide?

Moreover, since the device type test is judged manually by the tester, for the PTP with external buttons, can we continue to report the device type as "discrete Pad" and manually pass the test? 

For the previous PTP modules reported as discrete pad that have passed certification, do they need to be modified to “No Pad(Device?) Type” and recertified for the future shipping?

If the previous product don’t need to be modified, any possibility for Microsoft to modify  the criteria of Device Type test for a non-clickable touchpad to “discrete Pad or No Pad(Device?) Type” ?

Thank you very much for your great support and hope to get a clear answer soon.

**Comment by aahill** [comment]
Hi @chsiuchen, I'm really sorry in the delay in getting back to you. I can definitely help you with this however! Can you tell me what test(s) you're referring to specifically?

**Comment by aahill** [comment]
If you encounter this issue again, feel free to reopen this and I'll see what I can do to help!
