### ISSUE TITLE
SkipLicense not fully documented in dism-app-package--appx-or-appxbundle--servicing-command-line-options.md

### ISSUE THREAD

**Issue by fatlamer** [MicrosoftDocs/commercialization-public#92]
Hello team,
I recently had the task to import Appx language packs to an offline image and came across an issue where .Appx packages cannot be imported. 
Then I found [this](https://social.technet.microsoft.com/Forums/lync/en-US/9f3ed3cd-a6ef-4007-a75f-dea2e7c2ac3a/how-to-add-my-appx-or-appxbundle-into-wim-file?forum=w8itproinstall) article and modifying the registry really helped.
It turns out that this is really needed for appx packages without a license xml file and using /SkipLicense option.

Can you add this as a step in [dism-app-package--appx-or-appxbundle--servicing-command-line-options.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/dism-app-package--appx-or-appxbundle--servicing-command-line-options.md)?

Kind regards,
Deyan Denev

P.S. The issue I had was with Windows 10 1709 Enterprise and dism from ADK 1709 (16299.15) installed on WinSrv2012R2.

**Comment by themar-msft** [comment]
Sideloading apps is with DISM, including the necessary registry key is documented here: https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/sideload-apps-with-dism-s14

**Comment by fatlamer** [comment]
Thanks, my bad, sorry!
